### ISSUE TITLE
(?) Get help for this page - Just remove it

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1376]
**OpenMage v20.0.5**

Go to Backend. On every page there is a **(?) Get help for this page** link on the top right of the page. All links point to deleted resources on Magento website. This link and all the garbage code should be removed from OpenMage to avoid confusion.

![sceenshot1](https://user-images.githubusercontent.com/8360474/104006784-a720bf80-51af-11eb-8e1a-850e2f6a72ce.jpg)

**Comment by colinmollenhour** [comment]
@Flyingmana do we have a copy of this documentation somewhere? It would be a shame for there to be no user docs at all.. I tried backing up dev docs at https://github.com/OpenMage/devdocs-m1 and https://github.com/OpenMage/devdocs but haven't figured out exactly what is in there..

**Comment by ADDISON74** [comment]
@colinmollenhour, @Flyingmana: Do we have any idea related to this issue?

In case it cannot be implemented I recommend a complete remove from the code.

**Comment by fballiano** [comment]
we have a copy of the documentation but... those hints were never used (also because the documentation was never translated and it really is not user friendly) so I'd like to create a PR to completely remove the "get help for this page" and this hint:

https://user-images.githubusercontent.com/909743/113433089-7333ef80-93d6-11eb-80d6-5433bcbb68a4.png

**Comment by Flyingmana** [comment]
yeah, I think it can be removed then.

Should we want to do something with it, we can still bring it back.

Also linking related Issue here: https://github.com/OpenMage/magento-lts/issues/1374
