### ISSUE TITLE
Aoe Schedule

### ISSUE THREAD

**Issue by Danieleeffe1** [OpenMage/magento-lts#1474]
Goodmorning everyone

I installed the Aoe Schedule module to have more control of all magento cron.

I installed OpenMage on a server with php 7.4

When I try to generate a shedule the serever gives me this error:

[Wed Feb 24 08:03:59.484526 2021] [php7:error] [pid 205364] [client 108.162.229.14:32440] PHP Fatal error:  Uncaught Error: Call to a member function generateSchedules() on bool in /var/www/html/magento2/openmage/app/code/community/Aoe/Scheduler/Controller/AbstractController.php:151\nStack trace:\n#0 /var/www/html/magento2/openmage/app/code/core/Mage/Core/Controller/Varien/Action.php(437): Aoe_Scheduler_Controller_AbstractController->generateScheduleAction()\n#1 /var/www/html/magento2/openmage/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage_Core_Controller_Varien_Action->dispatch()\n#2 /var/www/html/magento2/openmage/app/code/core/Mage/Core/Controller/Varien/Front.php(192): Mage_Core_Controller_Varien_Router_Standard->match()\n#3 /var/www/html/magento2/openmage/app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch()\n#4 /var/www/html/magento2/openmage/app/Mage.php(729): Mage_Core_Model_App->run()\n#5 /var/www/html/magento2/openmage/index.php(78): Mage::run()\n#6 {main}\n  thrown in /var/www/html/magento2/openmage/app/code/community/Aoe/Scheduler/Controller/AbstractController.php on line 151

I can imagine it depends on the php version, but i don't know php javascript languages etc etc.

Suggestions on how to fix the problem?

**Comment by colinmollenhour** [comment]
I don't think this is a problem with either OpenMage or PHP 7.4, the last lines in the backtrace are:

```php
        $scheduleManager = Mage::getModel('aoe_scheduler/scheduleManager');
        $scheduleManager->generateSchedules();
```
So it looks like Magento was unable to instantiate the 'aoe_scheduler/scheduleManager' model. No idea why that would be offhand but seems likely a local issue.

**Comment by Danieleeffe1** [comment]
thanks for the reply, I wrote to the aoe schedule group, they replied to
me, just update to the latest version available on github of the module

Il mer 24 feb 2021, 19:33 Colin Mollenhour <notifications@github.com> ha
scritto:

**Comment by kiatng** [comment]
https://github.com/AOEpeople/Aoe_Scheduler/issues/395

**Comment by ADDISON74** [comment]
This is a golden rule. When upgrading check the extensions and theme in a test environment. I recently had to update a website from 1.9.2.4 to OpenMage. Checking the extensions I found that Activo CatalogSearch did not work. I searched the Internet and I found that there was a new update that made the difference between the Magento versions, which was up to 1.9.3 and after. Once the new version was installed, I got the desired functionality. This was a happy case when the extension was maintained by the developer.

For those who have not used Activo CatalogSearch I consider it a very important extension. It comes to fix the default search mode of Magento so that the results are as expected. I would integrate it in OpenMage, as well as a modified ImaClean extension that offers the possibility to delete images of orphaned products in the /media/catalog/product directory.
