### ISSUE TITLE
PHP8 Fatal error: Zend_Controller_Request_Http

### ISSUE THREAD

**Issue by S0FTWEX** [OpenMage/magento-lts#1508]
### Preconditions (*)

Using OpenMage version 20.0.7

### Steps to reproduce (*)

1. I upgraded to PHP 8.0
2. Got Error: Got error 'PHP message: PHP Fatal error:  Cannot declare class Zend_Controller_Request_Http, because the name is already in use in /lib/Zend/Controller/Request/Http.php

### Expected result (*)

I suggest to remove file /app/code/core/Zend/Controller/Request/Http.php to fix this issue.

**Comment by Flyingmana** [comment]
@S0FTWEX do you have a rewrite of the class in app/code/ somewhere? Or where is it loaded from in your case?
Are you sure this error did not appear in previous PHP Versions?

**Comment by S0FTWEX** [comment]
I have no overwrite files, it's clean install of OpenMage 20.0.7. There was no error in previous versions of PHP. Magento itself has 2 instances of class Zend_Controller_Request_Http:

in /lib/Zend/Controller/Request/Http.php
and
in /app/code/core/Zend/Controller/Request/Http.php

These classes has almost the same content (99.5% of content is the same).
This error will not break the code, is only shown in log file.

Error disappeared after deleting file /app/code/core/Zend/Controller/Request/Http.php

**Comment by kiatng** [comment]
Ref https://github.com/OpenMage/magento-lts/blob/a04c1b22a9d7def41eab7e0392e69fdf71a5b757/app/Mage.php#L38-L48

and [PHP Doc on `include_path`](https://www.php.net/manual/en/ini.core.php#ini.include-path):

> PHP considers each entry in the include path separately when looking for files to include. It will check the first path, and if it doesn't find it, check the next path, until it either locates the included file or returns with an **E_WARNING** or an **E_ERROR**. You may modify or set your include path at runtime using `set_include_path()`.

My suggestions:
1. `/app/code/core/Zend/Controller/Request/Http.php` overrides `/lib/Zend/Controller/Request/Http.php`, so if you need to remove one of the files, then it should be `/lib/Zend/Controller/Request/Http.php`. But this does not address the real issue.
2. To help debug the the warning that @S0FTWEX received `PHP message: PHP Fatal error: Cannot declare class Zend_Controller_Request_Http, because the name is already in use in /lib/Zend/Controller/Request/Http.php`, can you temporary remove or change both filenames for PHP to throw an **E_WARNING** or an **E_ERROR**, may be it'll helpful to find out where it is called and provide clues on how the class is instantiated and why it does not follow the priotity set in `include_path`.
