### ISSUE TITLE
Remove "web installation" and separate the installation scripts

### ISSUE THREAD

**Issue by fballiano** [OpenMage/magento-lts#1563]
This is something I've never liked about Magento since 11 years I'm working with it.

In every project I remove install.php, app/design/install and /skin/install.

The whole installation procedure is run only once in the lifetime of a project (mostly in a development environment, not even on a production server) and I can't see any reason why hundreds of files should stay on production servers for all the lifetime of the project when they'll never be used (potentially opening to vulnerabilities).

The best scenario IMHO?
- this repo should have no install.php and web installation
- installation script is downloaded and run from a different repo (like the https://getcomposer.org/download/ way)

**Comment by ADDISON74** [comment]
Anyone should install OpenMage from scratch without efforts. WordPress, Joomla could be installed in browsers by average people who knows basics thinks like SFTP, cPanel.

I would keep the actual behavior but after installation I would change automatically the installation script file name to something random based on current date (e.g. install.php.20210421). Those two folders you mentioned are not taking too much space in the file system, they are negligible and harmless. 

I never deleted the folders or renamed the installation file. I created a rule in .htaccess and redirected those who access install.php to a dedicated charming page. Then Fail2ban identifies them in webserver access log and the IP's will be blocked from now on.

The only thing I don't like in Magento 1 installation process is that I should create a database before. The script is not able to create one for me.

Related to the installation in a production environment I personally had to do this several times because there were no backups and there were major errors in the integrity of the database. As usual I deleted /app/etc/local.xml and reinstalled Magento, being the only one to that server. Once I checked the situation came back to normal I reopened the firewall.

**Comment by colinmollenhour** [comment]
I agree about the access should be better removed after installation. Personally I have no use for the GUI but I could see a small segment that still "needs" it. The CLI is very handy to have around so I'm not sure about moving it to a separate module.

What do you guys think of the nginx setup? #1209 It uses an "allow-only" approach rather than 
"allow-all and restrict" approach which I think is much more secure by default and fool-proof (speaking as someone who accidentally deleted `var/.htaccess` once..)

One option would be to make accessing the `install.php` blocked at the nginx level when `app/etc/local.xml` or some other flag file created by the installer exists or doesn't exist. I think it's best to make sure these types of changes are git-friendly for those that use the git repo as their primary deployment mechanism so you don't have to commit deletions of core files that can cause conflicts later.

**Comment by fballiano** [comment]
> Anyone should install OpenMage from scratch without efforts. WordPress, Joomla could be installed in browsers by average people who knows basics thinks like SFTP, cPanel.

I don't think magento is the same thing as wordpress or joomla, 99% of the stores have agencies, almost none can run a store without a developer to help them.

Also, is CLI much more difficult to use than the web install? considering that the web install is very dated (and it looks and feels dates), prone to timeouts (which, in the case of magento2, made the experience so much worse than they had to remove it).

A vast majority of the modern systems have a "wget installscript && install" which also self-removes the installation.

It would be much easier to maintain a single installation system than two, and there would no need to have a graphic designer to maintain the GUI of the install system than almost none never uses.

**Comment by ADDISON74** [comment]
Recently I helped a friend who had no skills about web technologies to create a website from scratch. I recommended him to watch a few tutorials on YouTube before. Once he was ready he bought a domain, 1 year hosting. From cPanel he installed WP and did all steps to create the website (plugins, themes, content, etc.). In 2 months he did not require help from a developer and the website is just fine. 

**Current OM version**
- Advantages? Anyone can install OM from browser even when something wrong is happening after.
- Disadvantages? The installation file install.php remains in the file system, it can be access in browser but the installation won't run. Two folders with a size bellow 500KB will stay there in case the installation process is running again.

** Removing the current installation from OM Version **
- Advantages? No install.php and those 2 folders.
- Disadvantages? Someone should create a CLI program, then testing it intensively. Also maintaining it periodically. It should work in OS's like Windows/Linux/MacOS. Any user should learn the new installation process from a manual page. 

In my experience a lot of people are rejecting CLI programs because they find them complicated. Although my experience with Linux started when there were on market CDs with Yggdrasil/GNU I still have to read the manual for a command from time to time. OM should be for anyone not for advanced users. It is not worth investing time in this direction. not even to change the file name for install.php because a new installation only starts if the local.xml file is missing and that means "someone" has access to the server.

**Comment by ADDISON74** [comment]
@colinmollenhour: Thank you for asking me for an opinion. I didn't know about that proposal. It will be analyzed and I will post a point of view on that commit.

**Comment by fballiano** [comment]
> Recently I helped a friend who had no skills about web technologies to create a website from scratch. I recommended him to watch a few tutorials on YouTube before. Once he was ready he bought a domain, 1 year hosting. From cPanel he installed WP and did all steps to create the website (plugins, themes, content, etc.). In 2 months he did not require help from a developer and the website is just fine.

and you installed it throught the cpanel installer, not the web installation inside the platform :-)

> * Advantages? Anyone can install OM from browser even when something wrong is happening after.

cmon you're writing this sentence to make your point :-D
an unexperience user wouldn't understands the web installation steps

> * Disadvantages? The installation file install.php remains in the file system, it can be access in browser but the installation won't run. Two folders with a size bellow 500KB will stay there in case the installation process is running again.

it's just dated since many years and nobody is really maintaining it because almost nobody is using it

> * Disadvantages? Someone should create a CLI program, then testing it intensively. Also maintaining it periodically. It should work in OS's like Windows/Linux/MacOS. Any user should learn the new installation process from a manual page.

it already exists and it is not so tested already... like there's no documentation about the "db_pass" parameter. I tried it a couple of days ago and I had to check the source coed to understand what the heck was the name of the db password parameter...

**Comment by ADDISON74** [comment]
Magento 2 can be installed both in the browser and in the CLI. Here's how I see the situation. The moment we have such a program that can just as easily install OpenMage from the CLI we do a test for a while and ask for the others opinions. Then we decide whether to leave both variants or only the CLI variant. I'm not the type to take out something that works until I have at least as good an alternative. I don't reject the idea, but I think that a lot of ready-made commits that should be tested and integrated in OpenMage are a higher priority. If you get involved in this then I will support you as much as possible.

**Comment by fballiano** [comment]
<img width="1058" alt="Schermata 2021-04-22 alle 09 40 19" src="https://user-images.githubusercontent.com/909743/115683856-c2729d80-a34e-11eb-9f19-4e6c52b5f350.png">

**Comment by ADDISON74** [comment]
Good for them. They send all to learn terminal commands as the only one option.

**Comment by fballiano** [comment]
they did it because in M2 the web install was a timeouts hell and never worked. OM is not in the same situation because the installation is much quicker, but still :-)

**Comment by fballiano** [comment]
also, OM has a new adminhtml theme, but the web install uses the old one, which IMHO is not a coherent experience

**Comment by ADDISON74** [comment]
In all OM installations I manage the users wanted the old Magento style. Although the developer's work is to be appreciated in a world saturated with solutions people prefer the things they are taught.

**Comment by fballiano** [comment]
I don't like the new admin theme, but if that's the choice than it should be everywhere.

**Comment by Flyingmana** [comment]
I also want to throw a penny into the discussion:
I had talked with at least one person, who had no cli access for their hosting. They would be blocked from installing OpenMage if this would be removed.

**Comment by fballiano** [comment]
I guess they setup the cronjobs via cpanel or something like that.

Well, ok, I see that this is not the direction we want to go, so I'll close this proposal. I keep thinking that a webinstall is something useful to a target that is not what OM should pursuit (very, very, small projects) while I think OM (like M1 was) is just great for medium sized stores.

**Comment by ADDISON74** [comment]
@fballiano: Please do not abandon your idea. If you implement the code I will be glad to test it. We worked great together to improve your extension. I would keep this post open and let other people see it.

**Comment by fballiano** [comment]
We already have an install script so there's really nothing to do here, if we want to keep the web install.

I wouln't like to see OM become a tool for extremely inexperiences users that cannot have a CLI (which frankly nowadays also cheap hosting companies provide) because how can they really use the system if they've no idea on how to call a simple script.

And I woulnd't like to have to remove the installation components every time I upgrade, although it's not that big of a deal (I don't manage 100 OM projects so..)

I was removing the downloader loooong before the big security vulnerability was discovered and I believe that a piece of software that's never used shouldn't just stay there forever.
