### ISSUE TITLE
Create a subfolder with a collection of free modules

### ISSUE THREAD

**Issue by Danieleeffe1** [OpenMage/magento-lts#1580]
the idea is simple.

magento 1 is no longer supported and this is where Openmage is born.

There are a lot of great free modules for magento 1 that also work in openmage.

Some of these modules you might even want to consider integrating into Open mage

others have small bugs that are probably easily fixed, but since magento 1 is dead no one will take the time to fix it.

so I propose:
create a directory or a section in the dOpenMage project where to pour all the free modules or their links and, if possible, fix any bugs as happened with post # 1566 (by the way ... if another user wants to exploit that issues how do you find now that it's closed?!?!)

what do you think?

**Comment by Flyingmana** [comment]
we do have a documentation page where such modules can be listed https://openmage.readthedocs.io/en/latest/

you can see the source of it here: https://github.com/OpenMage/documentation.
If you think a specific module should be added there, just open an issue there with a link and maybe some words we should add as description.

**Comment by ADDISON74** [comment]
I think I am one of the few who has dedicated time to testing over the years hundreds of free and paid extensions for various projects. Now that the number of posts related to Magento 1 has dropped dramatically on the Stack Exchange and other forums, I think a section should be considered where anyone interested in finding an extension can get reliable information from people who have tested the solutions, Without spending time searching the Internet. 

The post must have a certain format: name of the extension, where to find it, what advantages it offers, whether it is maintained or not by the developer, known issues, depending on the price. 

Recently I tested @fballiano extension related to the management of orphan images for CMS pages, products and categories. My personal opinion is that if someone is interested to use this extension for solving a management problem in OpenMage 1 then he can find in this extension everything he wants. The developer accepts opinions, he is responding fast and releases new versions.

OpenMage project must be a living one not limited to just fixing bugs in the code. Only in this way we can maintain an interest in the near future. From the discussions I had with several paid extension developers, they were no longer considering Magento 1, but when they found out that the project continues, that it is maintained by many people who have had notable contributions over time, they reconsidered their opinions and left the products for sale. To eliminate such a good product seems to me a fundamental mistake, especially since it has an appropriate heritage.

Even Indiana Jones and the Fate of Atlantis is a game from 30 years ago, I will always play it with pleasure, because it has 3 variants of solving and is still spectacular.

**Comment by Danieleeffe1** [comment]
excellent,

 I have just inserted the link of an add to cart in the section indicated I have tried many, all from github and all with the same problem. all duplicate the configurable products in the cart. 


if you know a working one I would be grateful.

**Comment by fballiano** [comment]
A pointed out by @Flyingmana, we've https://openmage.readthedocs.io/en/latest/modules/index.html for that ;-)
