### ISSUE TITLE
Export page - Missing [Select All] feature on Skip column

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1597]
I really don't understand why the column **Skip** was left without a [Select All] check box. 

Let's say there are 250 attributes and I would like to export only SKU and special prices. As it is right now in OM I have to press the [Continue] button to export all rows then deleting the unwanted columns by editing the CSV file.

By adding a check box on the Skip column I can reduce the time spent in getting the information I want. With one click I select all rows then deselect those I need. There is no need to edit the CSV file and get rid off the other columns.

![Screenshot 2021-05-04 225217](https://user-images.githubusercontent.com/8360474/117063514-9d5a3380-ad2d-11eb-86fe-56e675f6e3c0.jpg)

**Comment by fballiano** [comment]
I did a quick test and only grids with "mass actions" have a "select all", but this grid doesn't have a mass action and adding one (which is the only way to show a "select all" link) wouldn't make any sense because there's no mas action to be done in this case.

It's gonna be very hard to add this feature...

**Comment by ADDISON74** [comment]
I close this issue as it is a feature request. We can continue discussions here #1657.

**Comment by ADDISON74** [comment]
@fballiano - let's continue the discussion here #1657.
