### ISSUE TITLE
Problem with logging into the admin backend

### ISSUE THREAD

**Issue by Marx15** [OpenMage/magento-lts#1606]
Hello everybody

I have another question as usual, unfortunately I can't get any further.

I had a Magento 1.9.3.3 installed and wanted to install 1.9.4.5 first so that I could make the jump to Openmage.

After upgrading to magento1.9.4.5 I had several problems so that I re-imported my backup.

Fronted is available again, but logging in to the backend is no longer possible.

Tried everything (I guess), all kinds of tips from the net. Unfortunately without success.

I would be very happy if someone can help me here.

No change would be made to the database. Only the files are deleted from the server and the backup is extracted to the folder that has been used up to now.
Php version is the same before the upgrade.

Many thanks for your help ;-)

**Comment by kiatng** [comment]
Have you looked at https://magento.stackexchange.com/questions/26071/magento-1-9-can-t-login-to-admin-panel?

**Comment by Marx15** [comment]
Thank you very much for your help.

Unfortunately, I've already read that and tried. Unfortunately without success.

I just can't get into the backend.

After entering my name and password, I get the message:
You did not sign in correctly or your account is temporarily disabled.

What also surprises me is that if I try to forget the password after entering the email address, nothing happens.

Maybe someone has another tip?

Thanks.

**Comment by ADDISON74** [comment]
My personal opinion that it is a useless stage 1933 -> 1945 -> OpenMage 20.0.10.

If it were up to me I would save the entire database. Then I would do an evaluation of the file system between what you have now and the Magento default 1.9.3.3 version to find the files that are not common (extensions, custom code, themes, ...). I will keep them and erase all that is common. Then I copy OpenMage the latest version to the file system. Load the Frontend/Backend. It should go smoothly. 

PS - This is not an issue related to OpenMage. I suggest closing this post and open one here if you ask for help: https://github.com/OpenMage/magento-lts/discussions.

**Comment by Marx15** [comment]
Many Thanks.

what I just don't understand is why you should actually make a backup if I can't use it? ;-(

Everything works except logging in to the backend.
Otherwise nothing was done by me.

I deleted the file from root after upgrading to Magento 1.9.4.5 and extracted the file from the backup in root. Caches deleted from the .../var/ folder. Cookies deleted from the browser and tried to log in.
Unfortunately without success.
Just a hint:
You did not sign in correctly or your account is temporarily disabled.
and then also:
Invalid form key. please refresh the page.

I'm pretty sure it's a small thing but a big impact :-(

I just want to go to the backend first ;-(

Thanks

**Comment by ADDISON74** [comment]
I told you my opinion on how to proceed. Now it depends on how long you want to invest in solving this problem. Any upgrade is done first in a test environment and then in production. You definitely want to be offered a solution here how to log in to Backend but I'm afraid you won't get one in time. Although at first glance it may seem like a small problem, it all starts with the upgrade you made. It's a matter of files since you ran a patch to get to 1.9.4.5.

**Comment by ADDISON74** [comment]
We exclude a solution to the problem related to the fact that you cannot log in to the Backend. Here's what you need to do in a test environment.

1. Back up your file system and database. A dump file and a copy in a new directory on your server.

2. Make a comparison for the file system between Magento default 1.9.3.3 and what you have now. It can be done in a folder comparison program. I recommend Araxis Merge. In this program you can also delete common files until you are left with what is different from Magento default (extensions, translations, theme, product images, ...). I can tell you that without making this comparison I can clean the system manually, without a script, in just 3-5 minutes because I know what are the default Magento files/directories.

3. Copy OpenMage files to what's left then access the Frontend. If it goes well access now the Backend. It will take some time because a few tables in the database will be modified by installation scripts. With the exception of these tables and the core_resource table, nothing changes in the database.

**Comment by Marx15** [comment]
I have now imported the last version of magento 1.9.4.5 again and I can now in the backend.

Just like yesterday I have the problem with this version (the reason why I have undone it) with the price in the shopping cart.

Prices are displayed correctly. Tax matches, however, the total amount is displayed incorrectly. Here is probably an additional 2 times the tax on shipping costs.

**Comment by ADDISON74** [comment]
We should close this issue because is not related to an issue in OpenMage.

**Comment by Marx15** [comment]
Thanks

**Comment by ADDISON74** [comment]
We should close open issues like this one. 

Please recommend to all from now one that for asking questions or support to use the new Discussions section.

**Comment by fballiano** [comment]
@Marx15  please close the issue
