### ISSUE TITLE
Question: what varnish module to use?

### ISSUE THREAD

**Issue by fballiano** [OpenMage/magento-lts#1625]
Hi everybody, openmage + php7.4 is extremely fast and, with my customers, we're super happy about it.

I've been using different FullPageCache solutions over the years (turpentine+varnish, some proprietary php based PFC extensions etc) and every time they were 90% working but we were constantly having small problems here and there.

So I'm here to ask you: what varnish extension do you think it's the best and most modern? Is it still turpentine? the official repo or some fork/branch (because the official one doesn't get an update since looooong time)?

Thanks everybody!

**Comment by ADDISON74** [comment]
This question should be in Discussions section.

For many years I was close to the Nexcess Turpentine project which was a very active one. In my opinion, the extension offered high performance when loading pages on crowded servers. If with an optimized PHP you could reach 76 requests per second with Varnish you could reach 2,000. I also used HHVM for a while but gave up when PHP 7.0 came out.

Unfortunately, those who maintained the project gave up without even handing over the baton to other people. Lately, Miguel Balparada was very bored to answer more questions, and if he did, he would not offer a solution. Thus, there are a lot of PRs that have not been integrated in the same way, there are problems where no answer has been given since mid of 2018. I have a great regret for what happened there.

The only issues I identified and could correct with ESI policy were related to the use of AJAX in pages. Otherwise it still works today, I even have an analysis of the extension with Varnish 6.1.1 where I identified only small correctable issues. FPC from different developers is not quite fast as Varnish based on a good configuration.

One person who supported the project is Jeroen Vermeulen who has been creating many PR's and seeing that they are not integrated has incorporated them into his own fork. You can find here his version: https://github.com/jeroenvermeulen/magento-turpentine.

If this project were resumed it would be a solution for OM especially since now VDS or DS have become cheaper than years ago and you can install ElasticSearch, Sphinx, Varnish to improve performance.

**Comment by fballiano** [comment]
wow! thanks @ADDISON74 this answer is pure gold!

I didn't ever notice the discussion section 😅🤦🏻‍♂️ so sorry! Should we move the topic there and close this one?

I've checked te jeroenvermeulen repo and it's great to have a new version but his repo doesn't allow for issues/pr so it's a bit limited, mmmm wondering if there's a way to resume something cause OM needs a reliable FPC module for the future (although the performance is very very good)

**Comment by ADDISON74** [comment]
We should keep Issues section for OpenMage. Please close this one and I will copy&paste my answer in Discussions.

**Comment by fballiano** [comment]
done: https://github.com/OpenMage/magento-lts/discussions/1626 :-)

**Comment by ADDISON74** [comment]
Great. Please post your comment next to my answer to continue the discussion.
