### ISSUE TITLE
Bot-attacks and 503 server errros

### ISSUE THREAD

**Issue by dbachmann** [OpenMage/magento-lts#1633]
Hey there, 

a customer of mine has a problem with some bot attacks. The urls which are opened by the bots lead all to a 503 server error and these urls appear also in the google search console. 

Here some examples
https://www.domain.com/en/directory/currency/switch/currency/GBP/uenc/aHR0cHM6Ly93d3cubmF0dXJlaG9tZS5jb20vZW4vbW90aGVyLXMtZGF5LWdpZnRzLmh0bWw_ZmFyYmU9MTI5JmFtcDslM0IlM0IlM0JjYXQ9NjIxJmFtcDslM0IlM0IlM0JpbmhhbHRfbD00NDMmYW1wOyUzQiUzQiUzQm9yZGVyPXBvc2l0aW9uJmFtcDslM0IlM0IlM0JkaXI9YXNjJmFtcDslM0IlM0JjYXQ9NjEzJmFtcDslM0IlM0Jncm9lc3NlPTE5MjIyNyZhbXA7JTNCJTNCb3JkZXI9bmFtZSZhbXA7JTNCJTNCZGlyPWRlc2MmYW1wOyUzQiUzQmxpbWl0PTkwJmFtcDslM0Jncm9lc3NlPTIwOTk2MCZhbXA7JTNCbGltaXQ9NjAmYW1wO2dyb2Vzc2U9MjMyMTEzJmFtcDtsaW1pdD02MA,,/

https://www.domain.com/de/directory/currency/switch/currency/DKK/uenc/aHR0cHM6Ly93d3cubmF0dXJlaG9tZS5jb20vZGUvdmFsZW50aW4tdW50ZXItMjAuaHRtbD8lM0JjYXQ9NjYyJmFtcDslM0IlM0JsaW1pdD05MCZhbXA7JTNCJTNCaW5oYWx0X2w9Njg3JmFtcDslM0JwPTImYW1wOyUzQmNhdD01NjImYW1wO2NhdD01ODUmYW1wO29yZGVyPXByaWNlJmFtcDtkaXI9YXNj/

https://www.domain.com/de/directory/currency/switch/currency/DKK/uenc/aHR0cHM6Ly93d3cubmF0dXJlaG9tZS5jb20vZGUvYnVlcm8tenViZWhvZXItaG9sei1jbGFzc2ljLmh0bWw_c2VyaWU9NzMxJmFtcDslM0JhbXAlM0JhbXAlM0JhbXAlM0IlM0JhbXAlM0JhbXAlM0JmYXJiZT00MDAmYW1wOyUzQmFtcCUzQmFtcCUzQmFtcCUzQiUzQmNhdD01ODYmYW1wOyUzQmFtcCUzQmFtcCUzQmFtcCUzQmxpbWl0PTkwJmFtcDslM0JhbXAlM0JhbXAlM0JhbXAlM0JjYXQ9NTkxJmFtcDslM0JhbXAlM0JhbXAlM0JjYXQ9NTkyJmFtcDslM0JhbXAlM0JjYXQ9NTg3JmFtcDslM0JjYXQ9NTg3JmFtcDtsaW1pdD05MCZhbXA7Y2F0PTU5MSZhbXA7b3JkZXI9cHJpY2UmYW1wO2Rpcj1kZXNj/

https://www.domain.com/de/deko-tablett.html?amp;amp;amp;amp;;limit=60&amp;;amp;amp;amp;;farbe=400&amp;;amp;amp;amp;;order=groesse_ca&amp;;amp;amp;amp;;dir=asc&amp;;amp;amp;amp;limit=90

https://www.domain.com/en/directory/currency/switch/currency/GBP/uenc/aHR0cHM6Ly93d3cubmF0dXJlaG9tZS5jb20vZW4vbW90aGVyLXMtZGF5LWdpZnRzLmh0bWw_ZmFyYmU9MTI5JmFtcDslM0JhbXAlM0IlM0JhbXAlM0JhbXAlM0IlM0JjYXQ9NjIxJmFtcDslM0JhbXAlM0IlM0JhbXAlM0JhbXAlM0IlM0JpbmhhbHRfbD00NDMmYW1wOyUzQmFtcCUzQiUzQmFtcCUzQmFtcCUzQiUzQm9yZGVyPXBvc2l0aW9uJmFtcDslM0JhbXAlM0IlM0JhbXAlM0JhbXAlM0IlM0JkaXI9YXNjJmFtcDslM0JhbXAlM0IlM0JhbXAlM0JhbXAlM0JjYXQ9NjEzJmFtcDslM0JhbXAlM0IlM0JhbXAlM0JhbXAlM0Jncm9lc3NlPTE5MjIyNyZhbXA7JTNCYW1wJTNCJTNCYW1wJTNCYW1wJTNCb3JkZXI9bmFtZSZhbXA7JTNCYW1wJTNCJTNCYW1wJTNCYW1wJTNCZGlyPWRlc2MmYW1wOyUzQmFtcCUzQiUzQmFtcCUzQmFtcCUzQmxpbWl0PTkwJmFtcDslM0JhbXAlM0IlM0JhbXAlM0Jncm9lc3NlPTIyNTA4MiZhbXA7JTNCYW1wJTNCJTNCZ3JvZXNzZT0yMTE1MDMmYW1wOyUzQmFtcCUzQnA9NSZhbXA7JTNCYW1wJTNCZ3JvZXNzZT0xODEwODYmYW1wOyUzQmtvbGxla3Rpb249Njc5JmFtcDtncm9lc3NlPTE4MDYyOSZhbXA7Y2F0PTYxMyZhbXA7bGltaXQ9NjAmYW1wO2xhZW5nZT0yMzIwODc,/

In a first step I blocked some ip-ranges but this is not the perfect solution. The urls are still there and when you start a check in the serch console these urls are also checked. 

The question is now, what to do with these urls and queries? The main issue is the cause of an server error.

**Comment by kiatng** [comment]
FYI, the jibberish in your sample URLs are base64 strings, which reveal your client site. I am not any good on things related to servers, but shouldn't invalid URLs be redirected to 404? When I tried in my installations, I got 404.

**Comment by Flyingmana** [comment]
any chance to get the related error which got logged?
Could be in the exception log, or the reports directory.
depending on what fails, its maybe in the php error log, or the webservers logs.

**Comment by ADDISON74** [comment]
Related to bots, an interesting aspect is that some of them are trying to download Magento files such as local.xml.bak, local.xml.backup. Many users who have access to the file system do not realize that renaming a file with such predictable extensions can create security issues.

I am server administrator with a long experience on Linux flavors, I have daily attempts from bots that either access Magento-specific URLs (app/etc/local.xml, /shell/, /var/export) or some related to phpMyAdmin, WordPress and many more. I do not recommend manual blocking IP's because it is time consuming, but it is good to check periodically the web server access log for identifying the bad guys. This way you can set REGEX expressions for Fail2Ban filters. I managed to clean daily attempts of almost 700 - 1000 IP's. Please pay attention to the ban time of these IPs it does not have to be long term. 30 days is enough to be released from jail. And do not use actions with iptables directly just use ipset. iptables chains if they are long enough the performance decrease the server performance. My iptables looks very basic and it is based on sets of ipset lists (bind, postfix, ssh, dovecot, countries, apache, magento, ...) and priority. It is also possible to redirect certain URLs to a specific page and then it is even easier to identify in logs. For example, if someone accesses /app/etc/local.xml you can redirect him to an porn website :)

Please note that you cannot anticipate anything but you can learn about these attacks if you check the webserver error and access logs daily. What you find in the logs is affordable compared to a DoS attack or a DDoS attack when you can not even access the server via ssh and sit calm and wait until the number of accesses is reduced. These days I have a bunch of IP's that try to exploit D-Link routers vulnerability (/HNAP1 in access log) but I identified the pattern in apache error log and access and I created a filter then Fail2Ban does the job for me.

**Comment by ADDISON74** [comment]
One more thing when I get records in Magento logs (exceptions, system) I check immediately based on the time from these logs who accessed the webserver at that moment and eventually any errors. MySQL, PHP logs are essentially too in investigations.

**Comment by dbachmann** [comment]
@ADDISON74 The problem is that I cannot add anything to the firewall. On my own servers i'm using fail2ban. On my customers server I can work only with the htaccess file. I am very restricted and my customer do not want to change the hoster. So I have to find another solution to handle this urls and exclude and/or remove them in the search console. 

@Flyingmana The logs do not show any error.

**Comment by Flyingmana** [comment]
@dbachmann 503 means there has to be an error somewhere, but it could be from any component of the stack. In worst case its a php segfault :/

any chance you are able to reproduce it on http://demo.openmage.org/ ?

but step by step, 
can you check if the request is logged in your webserver access log?
can you check if it does also appear in the php-fpm log?
Just to make sure it is not already failing on webserver or before

**Comment by ADDISON74** [comment]
The prices for VDS/VPS decreased dramatically in the last year. For 4 bucks you can book a KVM VPS with 2 vCore, 4GB RAM, 30GB NVME + 50 GB SSD. Magento 1 installed on a shared server is really a bad idea. With a VPS you have full control over the VM, privacy, packages.

The only way to mitigate these requests are by .htaccess usinng Redirect directives. Without root access you cannot do more. 503 means service unavailable and once the apache server is stopped you would like to know who starts it. It could be a fake alarm. If the route path is not related to one of your extensions I have serious doubts such of request could stop the webserver.

We should move this post to Discussions section.

**Comment by dbachmann** [comment]
Hey there, 

sorry for the late response. I could locate the errors. 
The first bug was a RewriteRule to .* - [R=503,L] in the htaccess. When a url met certain conditions the bots, including google, were redirected to a 503 error.... That was the first bug. But some urls still caused a 503 error. 

Then I tried to reproduce the second problem on the demo site. Everything worked fine there. When I asked for an actual apache configuration I was able to find the second bug. The module filter is not enabled and in the htaccess file is the following code 

`AddOutputFilterByType DEFLATE "application/atom+xml" \
                                      [ ... ]                                    
                                      "text/xml"`

When I added a condition to check if the filter module is enabled, everything worked fine again. 

@ADDISON74 Well, I know that servers are very cheap in this days. My customer knows that too and I offered him a dedicated server for a small amount of money. But my customer insists on a managed server and can't be convinced to run a server without any restrictions for me. So, at the end of the day he has to pay for my extra work.

**Comment by dbachmann** [comment]
@ADDISON74 Me too and my customer also ;) It is just the filter module which is not activated. When you can't access the server logs it is not so easy to locate the error. 

When I work with magento I'm using a very customized htaccess file to increase the performance. In the default .htaccess file there is only one line with AddOutputFilterByType and it is commented out. So with this one you won't find any error.
It would be great when magento/openmage would perform a check if the current system meet all requirements before the installation.

**Comment by ADDISON74** [comment]
I agree with what has been said. If you do not have access to the server configuration you need to see what options you have. Then you only rely on .htaccess, php.ini and hope it works. Having full access to a system and doing what you want is like sitting comfortably in the smartest armchair watching a movie on a big screen. Satisfaction guaranteed!

**Comment by dbachmann** [comment]
True story :D

**Comment by ADDISON74** [comment]
Please don't forget to close this issue.
