### ISSUE TITLE
maven_html5uploader not working

### ISSUE THREAD

**Issue by homerjsim** [OpenMage/magento-lts#1747]
I'am using OpenMage LTS 19.4.8 and installed Maven HTML 5 uploader from here https://github.com/OpenMageModuleFostering/maven_html5uploader

The problem is that the upload does not work, whe I try to upload a product image. The progressbar stops and when I click "save" in the product_page it redirects me to the login screen.
I tried to debug the JS (but this is too complex for me).  In the developer-tools for Chrome it reports an error in script.js line 99 but I do not know how to fix that.
Can anyone help?

**Comment by ADDISON74** [comment]
I am sorry I don't want to look like a bad person but this is a request for help for an extension saved by OpenMage Team from Magento website before Magento Connect was closed. If you want to have discussions and get some help close this report and post in the Discussions section. Thank you for your understanding.

The situation was completely different if by upgrading from one version to another of OpenMage suddenly the extension no longer worked.

**Comment by homerjsim** [comment]
You are not a bad person. I thought I ask the question here because the extension worked flawlessly before migrating to openmage.
But if it is better to post it in the discussion forum. No problem.

**Comment by ADDISON74** [comment]
I doubt anyone could identify your problem without testing the variants you used. Reproduction in a test environment of the two is crucial.

Until we establish that it is a real problem in the OpenMage code, everything is just a discussion. For this reason I have indicated to close this post and to open a new one in the section dedicated to Discussions.

**Comment by fballiano** [comment]
@homerjsim what does the extension do? cause there's no need for "non flash" uploaders since long time now.

**Comment by ADDISON74** [comment]
I think this extension has a drag&drop feature. Starting with Magento 1.9.3 the Flash uploader was replaced. There is no need to use other extension for uploading images. A few month ago I was able to get from Magento 1.9.4.5 only this code and insert it in 1.9.2.4 version. Poor user used an old version of Firefox blocked from updates in order to upload the product images. For some people there are tough times. If you ask them to switch to an updated version you almost kill their world.

**Comment by jouriy** [comment]
> A few month ago I was able to get from Magento 1.9.4.5 only this code and insert it in 1.9.2.4 version.
@ADDISON74 Why did you do that when there is official SUPEE-8788 patch for 1.9.2.4 with HTML5 uploader included? Is the store still unpatched as after the change all patches can not be applied seamlessly?

**Comment by jouriy** [comment]
> I'am using OpenMage LTS 19.4.8 and installed Maven HTML 5 uploader 

As @ADDISON74 said there is no need in HTML5 uploader extensions in OpenMage (and Magento since 1.9.3 version or with SUPEE-8788 patch) and this extension should be disabled during upgrade by changing `<active>` tag to `false` in `app/etc/modules/Maven_Html5uploader.xml` or uninstalled.

**Comment by ADDISON74** [comment]
@jouriy - the client did not want to use patches and wanted to remain on 1.9.2.4 untouched. Probably in the past he had a bad experience with that procedure. That's why replacing the files was a method he agreed with. He can also sleep peacefully knowing that he has his initial files saved. It is a big store but those who manage it are afraid of changes and even understand them. Many times I wanted to change something for the better and the opposite happened. When those who do not have programming notions have issues they will consider that you are the cause of them.

**Comment by Flyingmana** [comment]
Hi @homerjsim 

> I tried to debug the JS (but this is too complex for me). In the developer-tools for Chrome it reports an error in script.js line 99 but I do not know how to fix that.

The line is this: https://github.com/OpenMageModuleFostering/maven_html5uploader/blob/master/skin/adminhtml/default/default/js/maven_html5upload/script.js#L99

This just assigns the result of the ajax request, so you could check in the developer tools what response you get for the request happening there.
It looks like just a followup error, and the actual error happening on the server side.

**Comment by homerjsim** [comment]
I tried the developer tools and honestly I have given up on this.
As some of you already mentioned I do not need an extra addon for uploading
I disabled it and now I use the internal one. That ist enough for me.

**Comment by homerjsim** [comment]
I will close this issue because I do not need to use  the addon anymore.
