### ISSUE TITLE
Move customer from between websites

### ISSUE THREAD

**Issue by tomekjordan** [OpenMage/magento-lts#178]
Hi. very annoying dis-feature in Magento, cannot move customers from 1 website to another. both fields are disabled, but many times customers registered in site with different language than they like to use later. it should be normal opened field to edit freely by admin.
I know how to hack it in sql, but this is not for normal store admins.
Would be great to allow those changes.

[http://prntscr.com/eahc1d](http://prntscr.com/eahc1d)

I know that reason behind this disabling - is that multiwebsite can allows the same customer registered to different store - but maybe there could be added option to validate it and disallow field value change if customer exists in different website.

**Comment by fballiano** [comment]
IMHO to develop such a thing it's a big task for an extremely small usecase.

Websites are generally used for totally different stores with different catalogs and different products, move a customer from a website to another can lead to an extreme amount of problems (unexisting products in the target website, fiscal documents that are no longer valid in the target websites for the existing orders).

I understand that it could be helpful if you just created a customer by mistake in the wrong website but it seems too much of an overkill task for such a small situation.

I'm closing this issue since it didn't get any feedback in 5 years, please feel free to reopen it if you feel so, possibly with a PR, it would help us a lot.
