### ISSUE TITLE
weird hardcoded credit card message on checkout page

### ISSUE THREAD

**Issue by f1-outsourcing** [OpenMage/magento-lts#1953]
design/frontend/base/default/template/checkout/onepage/review/totals.phtml

```
     36     <?php if ($this->needDisplayBaseGrandtotal()):?>
     37     <tr>
     38         <td class="a-right" colspan="<?php echo $_colspan; ?>">
     39             <small><?php echo $this->helper('sales')->__('Your credit card will be charged for') ?></small>
     40         </td>
     41         <td class="a-right">
     42             <small><?php echo $this->displayBaseGrandtotal() ?></small>
     43         </td>
     44     </tr>
```

![english](https://user-images.githubusercontent.com/13450219/147979224-ac23cd0e-0941-4f4e-8f2e-ece3a70ce8d6.png)
![german](https://user-images.githubusercontent.com/13450219/147979227-ae84ae65-12c4-4ed1-bad7-b2d4089f597d.png)

**Comment by trabulium** [comment]
The check needDisplayBaseGrandtotal is when the Quote Currency is different to the Base Currency so the message appears. The real issue is why your Grand Total is $0.00,  I assume Gesamtsumme (great sum) is German for Grand Total. So the reason why "Your credit card will be charged for" is $0.00 is displayed when the card gets charge an Euros but you are display Pounds to the end user. If you want to add a German translation, you need to add 

"Your credit card will be charged for","Ihre Kreditkarte wird belastet mit"
to this file:
app/locale/de_DE/Mage_Sales.csv

**Comment by f1-outsourcing** [comment]
But this is not a credit card check out.

**Comment by fballiano** [comment]
I think it's just a wrongly written message, when base and current currency differ, there's this message appearing. The sentence should be different tho.
