### ISSUE TITLE
set_error_handler() has been disabled

### ISSUE THREAD

**Issue by f1-outsourcing** [OpenMage/magento-lts#1980]
I am constantly getting this error. I know many are not putting this as a disabled function. But my reasoning behind this, is that errors are not being redirected to different locations where the php/apache user can edit and/or delete them. Secured logs can be nice when something gets hacked.

[1]
PHP Warning:  set_error_handler() has been disabled for security reasons in /app/code/core/Mage/Core/Model/App.php on line 793

### Steps to reproduce (*)
disable php function set_error_handler

I am not sure why this error handler is even called so often. Better would be to try and set it once.
https://github.com/f1-outsourcing/magento-lts/commit/e241b7ed46e0b1fd98ce5ca0555220d98cfcda13

**Comment by f1-outsourcing** [comment]
> You could disable any functions but apparently the set_error_handler is needed for OM to run

No it is not needed. OM runs fine when this is disabled.

**Comment by fballiano** [comment]
but you could disable any other function, the core can't control that, at the moment the set_error_handler is a needed function, at least in my opinion

**Comment by Flyingmana** [comment]
We can see in https://github.com/OpenMage/magento-lts/blob/3dc7e684a334d313a2028fa6c7559a362dc9f6d9/app/code/core/Mage/Core/functions.php#L119 why it is needed.

While your system might work without it, it might not for others. Because it ignores certain errors which are "kind of expected but irrelevant" and it avoids showing errors to the frontend in production mode, so it is even required for security reasons.

If you hoster did disable the setting of the error handler for security reasons, you will need to find a solution with them.

Not sure what you mean with "often". Did you see it happen multiple times in a single request? that would be something to look into. Else, it happens at least once on every request by definition.
