### ISSUE TITLE
Backend Category Grid - Unable to select 'ANY' products in dropdown filter

### ISSUE THREAD

**Issue by git-seb** [OpenMage/magento-lts#2177]
### Preconditions (*)

1. OpenMage version 20.0.14

### Steps to reproduce (*)

1. Catalog > Manage Categories > Select category > Manage products
2. Above checkbox column, select 'Any' and click 'Search'

### Expected result (*)

1. After reloading it should show all products, selected and non-selected.

### Actual result (*)

1. After reloading, 'Any' has been changed to 'Yes' again. Only selected products show up.

**Comment by ADDISON74** [comment]
**I confirm this issue.**

I was able to replicate it in OpenMage 20.0.14. Please note it is not present in OpenMage 20.0.13. I will try to make a comparison between versions to understand what PR could create trouble.

This is **OpenMage 20.0.13 + Magento 1.9 Sample Pack**:

![om-13](https://user-images.githubusercontent.com/8360474/171380638-bad71254-17dc-4b96-899b-2d448f7b07b8.jpg)

**This is OpenMage 20.0.14 + Magento 1.9 Sample Pack**:

![om-14](https://user-images.githubusercontent.com/8360474/171380663-d151eba9-737c-4c3f-a343-7b8c2ded3483.jpg)

In OpenMage 20.0.13 if I choose "Any" from the list and press [Search] after reloading the page it stays "Any". It is not happening the same in OpenMage 20.0.14, even I choose "Any" from the list and press [Search] after reloading the page it stays as "Yes". It is strange that for "No" value it will not be switched. In conclusion, "Any" is assimilated as "Yes".

As an advice please do not upgrade your production stores without intensive testing before.

**Comment by ADDISON74** [comment]
Related to this reported issue, comparing version 20.0.13 with 20.0.14 there are a lot of changes in this directory /app/code/core/Mage/Adminhtml/Block/Widget/. Here is the list of files with changes:

Accordion.php
Grid.php
Grid/Interface.php
Grid/Radio.php
Grid/Text.php
Grid/Abstract.php
Grid/Abstract.php
Grid/Item.php

I did not have time right now to make a comparison for these files but I suspected Grid.php file as the one that creates trouble. I replaced it with the old version from 20.0.13 and the issue was solved. Once I will understand what is happening I will find what PR created the trouble. 

I would recommend to spend a few days to revise the list of all modifications introduced in 20.0.14 version. As you may know from the last version released almost 1 year has passed and there were no reported issues, but they are not delayed to appear with the new version and in this way I want to thank those who spend time finding and reporting them.

@git-seb - you can use this file /app/code/core/Mage/Adminhtml/Block/Widget/Grid.php from version 20.0.13. Please let me know if this temporary solution fixes your issue.

**Comment by ADDISON74** [comment]
I updated my previous comment. Two files were changed between version:

/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php
/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Massaction/Abstract.php

We should check both files even the last one did not create trouble.

**Comment by fballiano** [comment]
I would revert commit https://github.com/OpenMage/magento-lts/commit/2ae8c05aaa801c1b22bf0c649d60265dbaed684d since it seems to only add defaults when the parameter exists but it's empty, which is exactly the problem here, and shouldn't even be related to the original issue https://github.com/OpenMage/magento-lts/issues/820

**Comment by sreichel** [comment]
@all-contributors add @git-seb bug
