### ISSUE TITLE
Some mass actions in Orders grid don't have a confirmation dialog

### ISSUE THREAD

**Issue by elidrissidev** [OpenMage/magento-lts#2323]
Two days ago one of our team members accidentally canceled all pending orders thinking he applied an email filter. Luckily there were only a few orders at that time and we were able to un-cancel them quickly.

I think that in general all grids should have a confirmation dialog for potentially dangerous/destructive actions to protect from accidents like these. Any other suggestions to solve this are welcomed.

### Preconditions (*)
1. Any version of OpenMage.

### Steps to reproduce (*)
1. Go to Sales -> Orders and select some orders from the grid.
2. Choose "Cancel" or "Hold" action and click "Submit".

### Expected result (*)
1. There should be a confirmation dialog for potentially dangerous or destructive actions such as canceling orders.

### Actual result (*)
1. Actions are submitted without any confirmation.

**Comment by elidrissidev** [comment]
I don't know how feasible it is to also show in the confirmation dialog how many orders the action will apply to, that would help too.

**Comment by kiatng** [comment]
We removed the cancel item years ago
```php
/** @var Mage_Adminhtml_Block_Sales_Order_Grid $this */
$this->getMassactionBlock()->removeItem('cancel_order');
$this->getMassactionBlock()->removeItem('hold_order'');
```

**Comment by fballiano** [comment]
Some mass actions can be really dangerous so it would be nice to have a confirmation prompt, also a "are you sure?" is better than nothing.
But if we think about it... probably all mass actions are dangerous so should they all have a confirmation? But if we add a confirmation to every mass action... it's kinda like adding none since the users will get used to it and stop reading it.

So I really don't know what I would do here.

**Comment by elidrissidev** [comment]
@daboss84 Yeah, there's many different ways to tackle this, a warning will be a good first step. I will add this to my hacktober contributions list if no one picks it.
