### ISSUE TITLE
Sort by position does not work

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#2511]
### Preconditions (*)

1. 1.9.4.x-dev
2. flat product tables enabed

### Steps to reproduce (*)

```
        $collection = Mage::getResourceModel('catalog/product_collection')
            ->addCategoryFilter(Mage::getModel('catalog/category')->load(3))
            ->addAttributeToSort('position')
            ->load();
        var_dump($collection->getFirstItem()->getData());
```

```
Column not found: 1054 Unknown column 'cat_index.position' in 'order clause' ...
```

This works only for flat tables turned off.

There is a PR that fix this, but it does not work for me. See #1815

**Comment by elidrissidev** [comment]
From my testing, this error happens only when flat tables are ON and category filter is either not applied or category not found. Can you try commenting out the 3 lines below and see if your issue is resolved? Then I can create a PR.

https://github.com/OpenMage/magento-lts/blob/32d1591a91b0940661c130d3e2413c11867ff145/app/code/core/Mage/Catalog/Model/Resource/Product/Collection.php#L1535-L1537

**Comment by sreichel** [comment]
When i comment these line the error disappears ... not tested anything more.

**Comment by elidrissidev** [comment]
Why do you close this? The fix is not merged yet

**Comment by ADDISON74** [comment]
It is most likely the way in which Sven expresses his dissatisfaction with how this project is managed. Unfortunately, I cannot hide the fact that such actions which are repeated periodically affect me emotionally, especially since I still believe in OpenMage. I think that others are in the same situation.

**Comment by sreichel** [comment]
@elidrissidev i closed it b/c a dont we to see it anymore when viewing https://github.com/issues. Sorry.
