### ISSUE TITLE
Receiving "Coupon code is not valid" for newly created coupon codes 

### ISSUE THREAD

**Issue by andyt** [OpenMage/magento-lts#2561]
### Preconditions

1. OpenMage-LTS 19.4.16

We don't have any extensions installed that modify coupon code behaviour. 

### Steps to reproduce

1. Create a discount code that is expected to work - no conditions, no actions
2. Add items to shopping basket that would receive a discount with the newly created coupon code
3. Checkout and apply coupon code

### Expected result

1. Coupon discount is applied to basket.

### Actual result

1. "Coupon XXXX is not valid" message is shown.

I've attempted to debug this but without success. Any help greatly appreciated.

**Comment by elidrissidev** [comment]
I'm not able to reproduce this issue when checking out `v19.4.16` tag, neither with the latest changes on `1.9.4.x` branch. Is there anything else that you suspect could be causing this in your installation?

Can you also check if this condition is succeeding or not by putting a breakpoint on line 2024 or echoing something.

https://github.com/OpenMage/magento-lts/blob/7a4ba7bca07c115f0e52d35872f29c21c1f4cc01/app/code/core/Mage/Sales/Model/Quote.php#L2023-L2025

**Comment by ADDISON74** [comment]
Unfortunately, I did not manage to replicate this issue in OpenMage v19 latest, but a picture is worth a thousand words.

**First step**. I created a "Shopping Cart Price Rule". This is what I filled in "Rule Information" tab:
- Rule name: 2561
- Status: Active
- Website: Main Website
- Customer Groups: All selected
- Coupon: Specific Coupon
- Coupon Code: 1234

![1](https://user-images.githubusercontent.com/8360474/188747415-b46ebc7b-7a89-4894-8149-d8d53f3523d0.png)

**Second step**. This is what I filled in "Actions" tab.
Discount Amount: 10

![2](https://user-images.githubusercontent.com/8360474/188747433-5435027d-11a5-4394-8ef4-d5008b6db85c.png)

**Third step**. I added a product to cart. In the cart page I used in the "Discount Codes" input box ```1234``` then I clicked [Apply]. Page reloaded with message "Coupon code "1234" was applied."

![3](https://user-images.githubusercontent.com/8360474/188747654-bbec2aab-07c8-495e-9128-0913fac6a3a9.png)

In order to get "Coupon code is not valid" message, several conditions must be met.

**Comment by andyt** [comment]
Thank you for investigating. 

''''
 if (!$addressHasCoupon) { 
''''

is entering the block.

I notice that our installation has no option for selecting the website on the 'Rule Information' tab, as per your first image. We have only one website, but it looks as if your dev store does too. Could this be relevant?

**Comment by elidrissidev** [comment]
If it's entering the `if` block, it means the rule validator is removing the coupon from the quote. Can you show your coupon configuration?

**Comment by andyt** [comment]
![coupon-debug-1](https://user-images.githubusercontent.com/19744/188913859-45274b55-87a7-4aef-94ed-dcaba7d02ce1.png)
![coupon-debug-2](https://user-images.githubusercontent.com/19744/188913901-9a68db37-2f01-40b0-b5fa-283f51f26d22.png)

**Comment by elidrissidev** [comment]
Tried with your exact configuration but still can't reproduce it :/

<img width="909" alt="Screen Shot 2022-09-07 at 4 16 19 PM" src="https://user-images.githubusercontent.com/67818913/188915264-f1a6a850-d432-4015-8769-87ceaa42c22f.png">

**Comment by elidrissidev** [comment]
Pulling the ultimate debugging weapon here 😂, can you try putting the following code inside the Quote model:
```php
public function setCouponCode($couponCode)
{
    if ($couponCode === '') {
        mageDebugBacktrace();
        exit;
    }
    $this->setData('coupon_code', $couponCode);
    return $this;
}
```

What this will do is print the stack trace when the coupon code is removed from the quote, so we know what's causing it.

**Comment by andyt** [comment]
Thank you.

''''
[1] /var/www/htdocs/app/code/core/Mage/Sales/Model/Quote.php:2034
[2] /var/www/htdocs/app/code/core/Mage/Sales/Model/Quote.php:1507
[3] /var/www/htdocs/app/code/core/Mage/Checkout/controllers/CartController.php:607
[4] /var/www/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php:437
[5] /var/www/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php:262
[6] /var/www/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php:192
[7] /var/www/htdocs/app/code/core/Mage/Core/Model/App.php:381
[8] /var/www/htdocs/app/Mage.php:744
[9] /var/www/htdocs/index.php:88
''''

**Comment by andyt** [comment]
Putting this code in the Mage_Sales_Model_Quote_Address model does not trigger a backtrace.

**Comment by ADDISON74** [comment]
If we look in the code bellow we can see it when the error message is used, either when we don't have a coupon or when the length exceeds the maximum limit. In the present issue, both options are excluded, since the TESTING code fulfills both conditions.

https://github.com/OpenMage/magento-lts/blob/6081bf1e287ff981b12f72fb9626d90bb9174966/app/code/core/Mage/Checkout/controllers/CartController.php#L596-L628

As I proved above, in my installation which was based on DDEV + the latest cloned version of OpenMage v19 and Magento Sample Pack, I could not reproduce this issue. Something is wrong with that installation, I doubt that it is a test installation from scratch, there may be missing files from it, there may be other unknown issues. No matter how much I want to reproduce the problem, I can't.

@andyt - if what you have used so far is a test installation (no real data), you can make the used (OM files + the database dump) available to us in a repository. Regarding your question, if the absence of the Website from the form can influence the functionality, it has nothing to do with it.

**Comment by sreichel** [comment]
@andyt do you use other shopping cart rules?

**Comment by kiatng** [comment]
@andyt  Another debug method you can try:

```php
// In file app/code/core/Mage/Checkout/controllers/CartController.php line  611
             } else { 
                 $this->_getSession()->addError( 
                     $this->__('Coupon code "%s" is not valid.', Mage::helper('core')->escapeHtml($couponCode)) 
                 ); 
                // @andyt Add the following 2 lines
                $max = Mage_Checkout_Helper_Cart::COUPON_CODE_MAX_LENGTH;
                $this->_getSession()->addError("codeLength={$codeLength} ($max) ($isCodeLengthValid) quoteCode={$this->_getQuote()->getCouponCode()} ($couponCode)");
             }
```
Now apply the code in frontend, and then copy paste the second error message here.

**Comment by elidrissidev** [comment]
To give more context, it seems that the code that processes the rule inside `Mage_SalesRule_Model_Validator::process` doesn't reach the below line which sets the coupon code on the address:
https://github.com/OpenMage/magento-lts/blob/5974333faac3dee5c8a64345d7c2ff952af72a69/app/code/core/Mage/SalesRule/Model/Validator.php#L510

So my final suggestion is to set a breakpoint in the first line of that method and see in which line does it return.

**Comment by ADDISON74** [comment]
I made the modification recommended by @kiatng, but because in my case the coupon is applied, I put the piece of code instead of the success message. Here is the result in Frontend.

![error](https://user-images.githubusercontent.com/8360474/189092147-33ee4a86-9021-46f2-817c-33837302c643.png)

We have no information about the installation used by the author, if it is only an (OM + 1 Product + 1 Code) or a modified OM version. Without the files and the database used in testing, the post appears as a request for help, not as an error in the OM code. 

I also searched on Google for the error and did not find anything concrete that would lead to the conclusion that it is a real problem.

**Comment by ADDISON74** [comment]
Ihe problem is how we reproduce it. The discussion is from 7 years ago, Lee Saferite contributed during that time to OpenMage.

**Comment by andyt** [comment]
> Can you verify if you have any other rule with "Stop Further Rules Processing" set to Yes?

OMG. I'm so sorry everybody. This is the problem. We have a rule (which has been around a loooong time) for free shipping on orders over a certain amount, and for some reason that has "Stop further rules processing" to "Yes". We have other rules too, but they are even older than this free shipping one and I suppose for that reason they were not getting stopped. We are not using priorities.

Thank you all for your assistance, I'm so grateful and impressed by the responsiveness of the OpenMage community. I hope that this issue might help someone else in a similar position.

**Comment by ADDISON74** [comment]
Isn't that error message ambiguous? The coupon is valid but the message should be different than the current one. We would have solved the issue much easier.
