### ISSUE TITLE
Discount codes being used by who?

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#260]
Would it be possible to add a link here? Or order ID to the grid?

Or think of a "lookup order by coupon code" screen somewhere

![image](https://cloud.githubusercontent.com/assets/652395/25266460/757dfdd4-2671-11e7-8d97-f2553216699b.png)

We have always had business problems when a client asks "is this coupon code still valid" .... then we look it up here. See it is not valid. Then the question is: when was it used? by whom?

**Comment by colinmollenhour** [comment]
I hate to be a stick in the mud but this is starting to get into the realm of "new features" and not "bug fixes" which is not within the scope of this project.

Perhaps OpenMage would be a great place to start a sort of "super module" which accepts improvements and features that are more or less globally useful such as this one? Then magento-lts could be the recommended install platform and could accept minor improvements that make the "super module" possible without a bunch of messy rewrites and such (by adding new dispatchEvent calls in strategic places for example). Just a thought..

**Comment by seansan** [comment]
It's just a question possible issue

That store owners run into

Hence no coding no pull request

But a short description of the problem

**Comment by tomekjordan** [comment]
totally agree. weird request - what about multiple users who used the same coupon. I agree to fix Magento bugs, not to add any super-duper features - that will never be implemented officialy

**Comment by sreichel** [comment]
@colinmollenhour i think we are already behind this projects scope. There are a lot of merged PRs that extend/improve existing functions or add basic features - and do not fix a bug,

IMHO we should **not** add new features (like this), but we should ...

> accept minor improvements that make the "super module" possible without a bunch of messy rewrites and such (by adding new dispatchEvent calls in strategic places for example)

- new dispatchEvent / more named events
- new template placeholders (`$this->getChildHtml('some_block_before/after')`)
- improve internal functions (caching, indexing, url_rewrites ...)
- make base/rwd template more dynamic *
- support localization projects **(?)**

\* i was against touching template files, but with some tweaks some template-overrides would'nt be nessecary ....

E.g. `public function getAdditionalData(array $excludeAttr = array())`
in `...\Catalog\Block\Product\View\Attributes.php`
that is called in only one place `....\template\catalog\product\view\attributes.phtml`
to display all product attributes.

But it's called w/o parameter (`<?php if($_additional = $this->getAdditionalData()): ?>`), so that you can't manipulate output.

Why not change to `$this->getAdditionalData($this->getExcludeAdditionalAttributes())` add some logic to return empty array by default and so you can set attributes to exclude from beining displayed in `your_module_layout.xml`.

Edit:
`getAdditionalData(array $excludeAttr = array())` could also be changed to `getAdditionalData(array $excludeAttr = array(), array $attrCodeContions = array()), array $attrValueContions = array()` or add a new dispatchEvent to make it more flexible.

Just for example ... same for hardcoded image sizes.

**Comment by sreichel** [comment]
Adding colums to grids can be done with observers ... close?
