### ISSUE TITLE
Bug: when persistence checkout turned off; then persistent/customer/form/login.phtml still being used

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#282]
Bug: when persistence checkout turned off; then persistent/customer/form/login.phtml still being used

Actual
1. Turn [persistence checkout off](http://docs.magento.com/m1/ce/user_guide/sales/shopping-cart-persistent-setup.html) 
2. Go to checkout
3. login.phtml is being loaded from **persistent**/customer/form/login.phtml
idem for other forms there

Expected
3. login.phtml is loaded from checkout.xml + using checkout/onepage/login.phtml
(and not **persistent**/customer/form/login.phtml)

Also see: [link to LTS where loaded](https://github.com/OpenMage/magento-lts/search?utf8=%E2%9C%93&q=%22persistent%2Fcustomer%2Fform%22&type=)

**Comment by colinmollenhour** [comment]
This might not actually cause a problem, but the child blocks are still being added.. My preferred method of making optional updates like this is to add an event observer which adds a layout update handle that way the "if" can apply to the entire update and not just the actions. Would be more efficient if there was a custom event per controller though. The event I use now is 'controller_action_layout_load_before'.

**Comment by LeeSaferite** [comment]
@colinmollenhour This was my colution to that issue: https://github.com/AOEpeople/Aoe_Layout/blob/master/app/code/local/Aoe/Layout/Model/Layout.php#L45-L58

**Comment by colinmollenhour** [comment]
@LeeSaferite I definitely like that solution better, I was just proposing a less invasive solution that doesn't require modification of core classes or external modules to keep the issue focused on this particular bug.

However, since you mentioned it.. :)  I for one would be excited to see a PR which adds all of the Aoe_Layout functionality directly to core. While it is not exactly a bug fix, it is a serious improvement with no BC issues and is the way it "should have been done" to begin with.

**Comment by LeeSaferite** [comment]
And it could be much cleaner if it was in core TBH. :)

If people want it as part of core, I'd be more than happy to add it.

**Comment by colinmollenhour** [comment]
Assuming there is no licensing issue with AOE it has my vote.

I'm going to approve this PR in the meantime though since it does fix a bug.

**Comment by sreichel** [comment]
Should be fixed with #283.
