### ISSUE TITLE
admin create order -> shipping_as_billing is 0 when set shipping method

### ISSUE THREAD

**Issue by zamoroka** [OpenMage/magento-lts#305]
steps to reproduce: 
1. Create New Order from admin
2. Set "Shipping Address" Same As Billing.
3. Choose Shipping Method. 
> now Mage::getModel('Mage_Sales_Model_Quote_Address')->getSameAsBilling() == 1
4. Change Billing Address
5. Press "Update Items and Qty's"
6. Choose Shipping Method
> now Mage::getModel('Mage_Sales_Model_Quote_Address')->getSameAsBilling() == 0

**Comment by tomekjordan** [comment]
Save addres for new customer should be also chcked as default for admin orders.

**Comment by seansan** [comment]
@Tomek: as a merchant: I agree

**Comment by tomekjordan** [comment]
UPDATE: save adress for new customer - the same issue comes when you as admin create order for old customer but for other website - order gets all address data, but due to not-checked save address - new customer re-created for new websites has empty address in the customer account. so definitiely check SAVE address should be set by default. thanks!

**Comment by sreichel** [comment]
Fixed in #306.
