### ISSUE TITLE
ownerTree.container is undefined for product categories

### ISSUE THREAD

**Issue by luigifab** [OpenMage/magento-lts#3312]
With OpenMage 20.1.0-rc4, when I go to _Products > Any Product > Categories_, at store view level, I get the following error: `ownerTree.container is undefined`

https://github.com/OpenMage/magento-lts/blob/1431628ec5de406b7faf5ba2ed06ea02bcbd233d/js/extjs/ext-tree-checkbox.js#L65-L69

My 10 seconds solution is to replace, line 67/68 by: `var targetNode = n.parentNode ? n.parentNode.ui.getContainer() : (n.ownerTree.container ? n.ownerTree.container.dom : n.ownerTree.innerCt.dom);`

But I'm not sure why, and if it's only me.

**Comment by fballiano** [comment]
true, it's not only you

<img width="764" alt="Screenshot 2023-06-08 alle 22 19 20" src="https://github.com/OpenMage/magento-lts/assets/909743/1405c8f1-4741-4ed7-9ce6-4b9f7281eb44">

**Comment by elidrissidev** [comment]
Could possibly be related to the update made in #2473

**Comment by justinbeaty** [comment]
I will take a look at this today. It’s seems I did miss this instance of extjs being used in the backend.

**Comment by justinbeaty** [comment]
It would seem that just the following is enough to fix this:

```js
var targetNode = n.parentNode ?
    n.parentNode.ui.getContainer() : n.ownerTree.innerCt.dom;
```

Because of the comment on that line:

```
in later svn builds this changes to n.ownerTree.innerCt.dom
```

Recall that `ext-tree-checkbox.js` was not a part of ExtJS, but a plugin for ExtJS written by somebody many years ago. It seems they were aware that the newer version of ExtJS had a breaking change, and documented it in that comment. But since Magento never updated ExtJS, they never updated ext-tree-checkbox.

I am not sure that we need the nested tertiary code in @luigifab's original comment, unless we have some case where someone is still running the older ExtJS (which I'm not sure how that would happen.) It also doesn't hurt though, I guess.
