### ISSUE TITLE
Timezone Setting Not Reflecting Outside of Mage.php

### ISSUE THREAD

**Issue by samex** [OpenMage/magento-lts#3483]
### Issue Description:
Changing the timezone in various locations such as server settings, PHP settings, and Magento Admin (System > Configuration > General > Locale Options > Timezone) does not seem to reflect the desired timezone. Only changes made directly in `Mage.php` take effect.

### Steps to Reproduce:
Create a custom module and within an Adminhtml file, add the code to print the current timezone: `echo date_default_timezone_get();`
Alternatively, print the current DateTime object with: `print_r(new DateTime());`
Navigate to Magento Admin and verify the printed timezone.

### Expected Result:
The printed timezone should match the timezone set in Magento Admin (System > Configuration > General > Locale Options > Timezone).

### Actual Result:
The printed timezone is always "UTC", regardless of the server, PHP, and Magento settings.

### Additional Information:
This issue seems to be related to the `Mage.php` file. The timezone is permanently set to "UTC" due to this line:

https://github.com/OpenMage/magento-lts/blame/046450a07f4332ca8187ccf7011567b9231352c6/app/Mage.php#L828

https://github.com/OpenMage/magento-lts/blob/10b63c1f65bd38f4d75a1c049d9dedaf9dffddde/app/Mage.php#L828-L828

### Environment:

Openmage 20.0.20 ( I couldn't find my issue listed on GitHub issues. Could someone with a newer version please try to reproduce this to verify? )
PHP 7.4
Webserver: Apache

**Comment by kiatng** [comment]
Line 828:
https://github.com/OpenMage/magento-lts/blob/10b63c1f65bd38f4d75a1c049d9dedaf9dffddde/app/Mage.php#L828-L828

was there since time immemorial. To get local time set in the system config, use

```php
    /**
     * Return current local date and time
     *
     * @param string $format see http://www.php.net/manual/en/function.date.php
     * @return string
     */
    public function getLocalDateTime($format = 'd-m-Y H:i:s') {
        return Mage::getSingleton('core/date')->date($format);
    }
```

In admin backend, there are many columns in the grid with datetime. 
![image](https://github.com/OpenMage/magento-lts/assets/1106470/5a3da2f3-7d0c-4a54-9384-f71d3c9e2d21)

The datetime values are rendered in local timezone (by default):
https://github.com/OpenMage/magento-lts/blob/10b63c1f65bd38f4d75a1c049d9dedaf9dffddde/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Column/Renderer/Datetime.php#L52-L76

**Comment by elidrissidev** [comment]
I agree with @kiatng, the native date functions always returned UTC date and time. To get the store local date you need to use one of the many ways provided by Magento. You may re-open this if you have further questions.
