### ISSUE TITLE
The TinyMCE bullet menu stays on top

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#3733]
Steps to reproduce this issue:

1 - Go to **Backend > CMS > Pages** and select a page for editing
2 - Activate TinyMCE editor by pressing **[Show / Hide Editor]**
3 - Click on the three horizontal bullets icon **[...]** at the right to show hidden menu and let it visible
4 - Click on **[Variables]** and **[Widgets]** buttons

Both "Insert Variable..." and "Insert Widget..." windows are behind the menu instead of being in front of it. In addition, that menu, even if it remains visible, should be covered by the gray background, which is not.

Please see the image bellow

![overlay](https://github.com/OpenMage/magento-lts/assets/8360474/5b03190f-0db8-435a-93f4-5885bbb4910c)

**Comment by sreichel** [comment]
Note: when you hit "Insert widget" window z-index increases with 2 with every click ... (?!?!)

... needs some investigation.

**Comment by fballiano** [comment]
> Note: when you hit "Insert widget" window z-index increases with 2 with every click ... (?!?!)
> 
> ... needs some investigation.

I've analyzed the code and it was done that way to manage situations when multiple overlays are opened one after each other. This way the last opened overlay stays always on top of the previous one. Having a fixed zindex wouldn't have worked.

Also, it's increased by 2 because 1 is for the backdrop and 1 is for the actual modal "window".
