### ISSUE TITLE
Fatal error:  Uncaught Error: Call to a member function addData() on null

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#3811]
OpenMage 20.3.0
Magento Sample Pack
PHP 8.3
MAGE_IS_DEVELOPER_MODE=1

**Steps to reproduce this issue**

1 - Go to the **Backend > System > Import / Export > Dataflow - Advanced Profiles**
2 - Click on the **[Add New Profile]** button
3 - Fill in "New Profile" and "Action XML" then click the [Save and Continue Edit] button

**You will get this error**

```php
Fatal error:  Uncaught Error: Call to a member function addData() on null in /var/www/html/app/code/core/Mage/Adminhtml/controllers/System/Convert/ProfileController.php:119
Stack trace:
#0 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(421): Mage_Adminhtml_System_Convert_ProfileController->editAction()
#1 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(255): Mage_Core_Controller_Varien_Action->dispatch()
#2 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(181): Mage_Core_Controller_Varien_Router_Standard->match()
#3 /var/www/html/app/code/core/Mage/Core/Model/App.php(358): Mage_Core_Controller_Varien_Front->dispatch()
#4 /var/www/html/app/Mage.php(760): Mage_Core_Model_App->run()
#5 /var/www/html/index.php(56): Mage::run()
#6 {main}
  thrown in /var/www/html/app/code/core/Mage/Adminhtml/controllers/System/Convert/ProfileController.php on line 119
```

This is the PHP file and the line:

/app/code/core/Mage/Adminhtml/controllers/System/Convert/ProfileController.php:119

**Comment by kiatng** [comment]
I cannot replicate this error. 

Ref https://github.com/OpenMage/magento-lts/blob/c5b35aa9da03142873ddd22af7cca0ebcb077bd9/app/code/core/Mage/Adminhtml/controllers/System/Convert/ProfileController.php#L30-L53

which is called in https://github.com/OpenMage/magento-lts/blob/c5b35aa9da03142873ddd22af7cca0ebcb077bd9/app/code/core/Mage/Adminhtml/controllers/System/Convert/ProfileController.php#L108-L110

`$profile` cannot be null because of line 37 `$profile = Mage::getModel('dataflow/profile');`.

It must be something else for you to get 
> Fatal error:  Uncaught Error: Call to a member function addData() on null

Is the dataflow module disabled or is it missing? Regardless, it is more probable that something is wrong with your particular instance rather than OpenMage.

**Comment by ADDISON74** [comment]
It is OpenMage 20.3.0 cloned and updated. I am using the Magento Sample Pack to get data and simulate almost everything. Debian 12 + PHP 8.3. There are no other changes, I didn't change any setting in the Backend. 

I will investigate what you requested.

**Comment by ADDISON74** [comment]
This proves the error based on the configuration mentioned in the initial post

https://github.com/OpenMage/magento-lts/assets/8360474/4fc8b213-afbe-40ea-88ce-8f4cba549ca9
