### ISSUE TITLE
Error during unserialization

### ISSUE THREAD

**Issue by urbancrew** [OpenMage/magento-lts#386]
Anyone noticed the exception with message 'Error during unserialization'. It happens in magento 1.9.3.x when you go to magento system > configuration > design:
when you are there just change from default scope to a website and then you'll receive this message in var/log/exception .log:

```
2017-11-22T10:24:43+00:00 ERR (3): 
exception 'Exception' with message 'Error during unserialization' in lib/Unserialize/Parser.php:60
Stack trace:
#0 app/code/core/Mage/Core/Helper/UnserializeArray.php(44): Unserialize_Parser->unserialize(Object(Mage_Core_Model_Config_Element))
#1 app/code/core/Mage/Adminhtml/Model/System/Config/Backend/Serialized.php(37): Mage_Core_Helper_UnserializeArray->unserialize(Object(Mage_Core_Model_Config_Element))
#2 app/code/core/Mage/Core/Model/Config/Data.php(78): Mage_Adminhtml_Model_System_Config_Backend_Serialized->_afterLoad()
#3 app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(334): Mage_Core_Model_Config_Data->afterLoad()
#4 app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#5 app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#6 app/code/core/Mage/Adminhtml/Block/System/Config/Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm()
#7 app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm()
#8 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_System_ConfigController->editAction()
#9 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#12 app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 index.php(83): Mage::run('my_website...', 'website')
#14 {main}
```

**Comment by tomekjordan** [comment]
Install Atwix patch for it

**Comment by urbancrew** [comment]
which one is that?

**Comment by tomekjordan** [comment]
https://github.com/Atwix/Atwix_Unserialize

**Comment by lfluvisotto** [comment]
@urbancrew What is your PHP version?

Here using PHP 5.6.32 is working normally.

**Comment by urbancrew** [comment]
our php version is 5.6.32. installing the Atwix extension helped.
Thanks!

**Comment by morrisstrangfeld** [comment]
This issue still exists. It is especially bad if it happens after login with quote item.
The password of the user is revealed in the exception which is especially bad.
It is described here:
https://www.atwix.com/magento/supee-7405-cart-merge-error-fix/

`
Exception: Error during unserialization in /var/www/html/lib/Unserialize/Parser.php:60
Stack trace:
#0 /var/www/html/app/code/core/Mage/Core/Helper/UnserializeArray.php(44): Unserialize_Parser->unserialize('grouped')
#1 /var/www/html/app/code/core/Mage/Sales/Model/Quote/Item.php(540): Mage_Core_Helper_UnserializeArray->unserialize('grouped')
#2 /var/www/html/app/code/core/Mage/Sales/Model/Quote.php(1889): Mage_Sales_Model_Quote_Item->compare(Object(Mage_Sales_Model_Quote_Item))
#3 /var/www/html/app/code/core/Mage/Checkout/Model/Session.php(303): Mage_Sales_Model_Quote->merge(Object(Mage_Sales_Model_Quote))
#4 /var/www/html/app/code/core/Mage/Checkout/Model/Observer.php(44): Mage_Checkout_Model_Session->loadCustomerQuote()
#5 /var/www/html/app/code/core/Mage/Core/Model/App.php(1410): Mage_Checkout_Model_Observer->loadCustomerQuote(Object(Varien_Event_Observer))
#6 /var/www/html/app/code/core/Mage/Core/Model/App.php(1389): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Checkout_Model_Observer), 'loadCustomerQuo...', Object(Varien_Event_Observer))
#7 /var/www/html/app/Mage.php(494): Mage_Core_Model_App->dispatchEvent('customer_login', Array)
#8 /var/www/html/app/code/core/Mage/Customer/Model/Session.php(262): Mage::dispatchEvent('customer_login', Array)
#9 /var/www/html/app/code/core/Mage/Customer/Model/Session.php(247): Mage_Customer_Model_Session->setCustomerAsLoggedIn(Object(Mage_Customer_Model_Customer))
#10 /var/www/html/app/code/core/Mage/Customer/controllers/AccountController.php(159): Mage_Customer_Model_Session->login('XXXX', 'XXXXXX') // here the PW is revealed
#11 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(437): Mage_Customer_AccountController->loginPostAction()
#12 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage_Core_Controller_Varien_Action->dispatch('loginPost')
#13 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(192): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#14 /var/www/html/app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch()
#15 /var/www/html/app/Mage.php(729): Mage_Core_Model_App->run(Array)
#16 /var/www/html/index.php(78): Mage::run('default', 'store')
#17 {main}`

I think it makes sense to fix that in openmage instead of relying on this atwix module which clearly no one knows about in the first place.
