### ISSUE TITLE
Skipped Zend_Validate_Barcode_Intelligentmail from autoloading

### ISSUE THREAD

**Issue by S0FTWEX** [OpenMage/magento-lts#4002]
OpenMage 20.8.0
PHP 8.2

When I want to optimize autoload files with `composer dump-autoload --optimize` I get a notice:
`Class Zend_Validate_Barcode_Intelligentmail located in ./vendor/shardj/zf1-future/library/Zend/Validate/Barcode/IntelligentMail.php does not comply with psr-0 autoloading standard. Skipping.`

What is the problem with this class?

**Comment by pquerner** [comment]
According to latest release, the filename should be `IntelligentMail.php` instead of `Intelligentmail.php` (notice the upper `M`).
https://github.com/Shardj/zf1-future/blob/release-1.234/library/Zend/Validate/Barcode/Intelligentmail.php

Its been reported here https://github.com/Shardj/zf1-future/issues/66 and was apparently fixed but was unfixed again here https://github.com/Shardj/zf1-future/pull/336.
