### ISSUE TITLE
Recent merges, leading to Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#413]
Hi we are testing the latest 1.9.3.x (actually the previous before all pushes/merges from 13-12 and 14-12)

We now see many lines of mem exhausted. Can this have something to do with recent changes?

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /var/www/html/shirts/public_html/lib/Zend/Db/Statement/Pdo.php on line 228
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 44800000 bytes) in public_html/lib/Zend/Db/Statement/Pdo.php on line 228

Sorry that I ask here - but that is like the only source I can think of (because it also happens all the time, everywhere)

**Comment by colinmollenhour** [comment]
Usually when I've seen this error message it is because there is a query that is returning a large result set, such as an entire collection being loaded without a filter when really only a subset of rows are needed. This could also not exhibit itself as a fatal error until the size of the table being queried grows to a size large enough to exhaust memory. So just because it started happening recently doesn't mean the bug has not been present much longer. 

That second line indicates that the db driver is trying to allocate 44MB of memory all at once! That is a lot, are you storing videos or huge images or something as BLOBs? Enable the general query log and look at the last query for each thread id and that might expose the query responsible.

**Comment by colinmollenhour** [comment]
Tool I wrote for capturing general query log: https://gist.github.com/colinmollenhour/5646619

**Comment by dvdsndr** [comment]
I have seen this issue due to badly written modules. One php process looping and not releasing memory. The point where php gives was not actually the problem. Found the problem by using NewRelic.
