### ISSUE TITLE
QTY max limit per website, instead global

### ISSUE THREAD

**Issue by tomekjordan** [OpenMage/magento-lts#438]
Hi. any options to add/fix this fields "(min, max) QTY allowed in the cart" for product's inventory tab. Now its limited to global scope, but any multistore needs flexibilty for this. Any option to make it per website?

thanks
Tomek

**Comment by colinmollenhour** [comment]
It is not a small change since these fields are in `cataloginventory_stock_item` table which contains only fields that are set per-"stock" (although Magento only ever had 1 stock). To make this per-store would require pretty significant changes to database structure and code almost certainly breaking BC somewhere so it might be best to do this with an extension if it is really necessary.

**Comment by sreichel** [comment]
Haha. Also checked if its enough to change config scope today ... but its not.
