### ISSUE TITLE
Microsoft & GitHub

### ISSUE THREAD

**Issue by Quazz** [OpenMage/magento-lts#487]
I was wondering if people here are concerned by Microsoft taking over GitHub in the near future. 

Obviously things wouldn't change in any drastic way straight off the bat, but we all know how these acquisitions go. Before long we'll need Microsoft accounts, get ads and need to pay for what should be default features. 

I'm personally still hoping for the deal to fail at some point, but it seems unlikely if they're making announcements about it.

What do you guys think?

**Comment by andreasemer** [comment]
Currently there is a lot of hype on social media about the possible (bad) changes in Github, but there is nothing concrete. 

I don't think the changes in the future will be bad, and if they will be, a project can also switch to another plattform than.

**Comment by Dmole** [comment]
All paying projects should move to gitlab so the money goes into the further development of open source. (but that's nothing new)

All projects that are freeloading should move to github to let Micro$oft foot the bill (in order to avoid burdening gitlab).

why gitlab?

- it's the most popular alternative [vs](https://thishosting.rocks/best-github-alternatives/)
- it has ab open source version used by Debian.
- it uses google cloud (and google makes open source like android and chromium) [ref](http://www.datacenterknowledge.com/cloud/how-did-gitlab-scale-slashdot-effect-point-and-click)

**Comment by colinmollenhour** [comment]
Let's just keep calm and see what happens. Microsoft is an evolving company and they are taking huge steps in the right direction in my opinion so I don't see why this is such a bad thing. Github has always been a for-profit organization and their platform was never OSS to begin with so I don't see what all the fuss is about.

If there is a real reason to move at some point I would second that GitLab is a great choice. But I don't see any reason to move right now.
