### ISSUE TITLE
Is Anchor categories: "still" including products from child categories that are disabled

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#561]
Is Anchor categories: "still" including products from child categories that are disabled

Basis
- 1 parent category set to is anchor = yes
- 2 children categories

Expected
- parent category contains products from both chidlren

Reproduce problem
- disable 1 of the 2 child categories

Expected
- parent category contains products from 1 child category

Actual
- still both

https://magento.stackexchange.com/questions/11632/magento-is-anchor-shows-products-from-disabled-subcategories

**Comment by fballiano** [comment]
To me this is debatable, in my opinion it's not a big deal if you get the products from all the subcategories, disabled or not, cause i've never thought disabling a category would somehow disable their product.

And since this didn't get any attention in more than 3 years I'm closing the issue. Anybody is welcome to re-open it if you feel so, please provide a PR cause it's really difficult to test and fix all the issues.
