### ISSUE TITLE
Patch SUPEE-10975

### ISSUE THREAD

**Issue by cundd** [OpenMage/magento-lts#579]
To bring this onto the table: Is there already a roadmap for integrating the [SUPEE-10975](https://magento.com/security/patches/supee-10975)?

**Comment by Niko9911** [comment]
PR was merged today. Feel free.

**Comment by colinmollenhour** [comment]
Note that the latest Magento has a regression in the attribute code validation which would let special characters be used in an attribute code and also would fail validation for some otherwise valid attribute codes. No idea if this is a security risk somehow but it could possibly be since `Varien_Object` traverses into child objects when the key contains `/`. See comment here: https://github.com/OpenMage/magento-mirror/pull/70#pullrequestreview-181513951

**Comment by Niko9911** [comment]
Please post this into Magento official. Posting this into mirrors doesn't help at all.

**Comment by Niko9911** [comment]
Only specifying problem here in public, can lead information to be fallen into wrong hands. Please send this to official repo. As official repo is fixed, this will be fixed in mirrors

**Comment by Niko9911** [comment]
@colinmollenhour

**Comment by colinmollenhour** [comment]
There is no official repo, dude!

**Comment by Niko9911** [comment]
@colinmollenhour You do not need git repository to create a bug report.

If you want your fix into this repo, why you don't create PR then or new issue?

**Comment by colinmollenhour** [comment]
I'll happily create a PR here, but as of now this bug does not exist in this repo yet.

**Comment by seansan** [comment]
I received note there is a problem with this patch. Cases have been
reported that one cannot save customer groups anymore after this update.
