### ISSUE TITLE
new 1.9.4.x Branch, how to handle it and align the process?

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/magento-lts#580]
with a new minor version, we semantically need a new branch, which will lead to some problems and questions.

Its to note, the changes in this minor release are not as big as usual.

1. Should we change all PRs to the new Branch?
2. Will the 1.9.3.x branch still be maintained?
3. How many bugfix releases should we wait, till we change the default?

I will push the merged release shortly as this new branch

**Comment by Flyingmana** [comment]
among the resolved conflicts

* docblocks we added
* empty lines
* spaces

there is a conflict in the `app/code/core/Mage/Wishlist/Model/Observer.php` regarding the wishlist. Its conflicting with the original official 7.2 Patch. And after looking through the code, it seems the patch is right, not the new release.

Thats kind of a special case we have here, and I should probably for a clean follow up, merge the wrong one, and do a PR to fix it again with what we had before...But that is so much unnecessary complicated work.

**Comment by Flyingmana** [comment]
https://github.com/OpenMage/magento-lts/tree/1.9.4.x

**Comment by colinmollenhour** [comment]
Thanks for getting the 1.9.4.x branch up!

I'm not sure why they bumped the 3 to 4 since it seems to just be a minor security update, but to avoid confusion I think we should stick with the convention and make 1.9.4.x the new "master".

In my opinion all existing PRs should be based on 1.9.4.x before being merged and 1.9.3.x will no longer be maintained unless there is an official 1.9.3.11 (or maybe not even if there is). Because we have very limited resources and there should be nothing preventing 1.9.3.x users from just switching to 1.9.4.x (disclaimer: still perform tests!) there is no reason to spend time applying updates to both branches.

**Comment by edannenberg** [comment]
Sounds like a good chance to start with clean base though. Most of the work is already done in my fork.

**Comment by cundd** [comment]
Does this fix #579 ?

**Comment by Flyingmana** [comment]
I think so, it may be worth to apply the patch to the 1.9.3.x branch anyway if we keep the new minor release in a new branch

**Comment by niclashoyer** [comment]
@Flyingmana 
is the 1.9.4.x branch ready, or are there any missing patches/fixes?

**Comment by Flyingmana** [comment]
Yes and Yes <.<

It absolutely is ready.

But there are also some recent patches which did not yet get ported(merged) from the 1.9.3.x into the 1.9.4.x
I will take care of applying them this week.

**Comment by seansan** [comment]
>> But there are also some recent patches which did not yet get
ported(merged) from the 1.9.3.x into the 1.9.4.x
>> I will take care of applying them this week.

Thumbs up +1

**Comment by Flyingmana** [comment]
just updated the 1.9.4.x branch with the latest merged patches of 1.9.3.x

**Comment by colinmollenhour** [comment]
Any reason not to go ahead and make 1.9.4.x the "Default branch"?

**Comment by Flyingmana** [comment]
yes, waiting for an "official" 1.9.4.1 release (I made a habit out of it to not trust .0 releases regarding stability) and forward-porting patches is a lot easier then back-porting them

**Comment by colinmollenhour** [comment]
Sounds good. Thanks!

**Comment by seansan** [comment]
+1

**Comment by edannenberg** [comment]
Opened a PR for some inconsistencies I found during my review. The 1.9.4.x branch is also currently missing https://github.com/OpenMage/magento-lts/commit/c86cbd9dc410174eecabb930e3a68ed8bf027f3a from 1.9.3.x.

Looks good otherwise.

This is probably the last chance for a clean 1.9.4.x main branch in this repo so I gonna bring this up one last time before I shut up. :) https://github.com/edannenberg/magento-lts/commits/1.9.4.0 is pretty much identical to 1.9.4.x. Would just need another rebase pass to improve my broken english in commit messages plus merging some changes to non-Magento related files like `README.md`, which I didn't bother to update over time.

**Comment by barryvdh** [comment]
Shouldn't there be a 1.9.4.0/1.9.4.1 branch?
> Each Magento 1.<minor>.<revision> release will get its own branch (named 1.<minor>.<revision>.x) that will be independently maintained with upstream patches and community bug fixes for as long as it makes sense to do so (based on available resources)

**Comment by Flyingmana** [comment]
1.9.4.0 to 1.9.4.1 is semantically a bugfix release. Maintaining bugfixes and patches for both of these versions is not providing a benefit as theoretically we would need to backport all the patches from 1.9.4.1 to 1.9.4.0, or what are the expectations you have for having them in separate branches?

**Comment by barryvdh** [comment]
I think I've misunderstood it indeed, the 1.9.4.x branch contains all fixes from 1.9.4.0/1.9.4.1, but you're not actively tagging release versions, so we should just require the branch.

**Comment by Flyingmana** [comment]
Process seems to be aligned for a while now, so closing :)
