### ISSUE TITLE
Zend_Http_Client problem with HTTP2

### ISSUE THREAD

**Issue by felipegomesdev** [OpenMage/magento-lts#659]
When using the Zend Client in the file

> lib/Zend/Http/Response.php

 method "extractVersion" line 478 , if the response is with HTTP2 protocol, a 503 error is received.

I noticed this because the dashboard graphics are not working.

![Captura de tela de 2019-04-11 14:59:22](https://user-images.githubusercontent.com/6062121/55980284-83db8000-5c6a-11e9-9ee2-b1191d19e8d5.png)
![Captura de tela de 2019-04-11 14:59:50](https://user-images.githubusercontent.com/6062121/55980285-83db8000-5c6a-11e9-99fc-6a7c81b948fd.png)

**Comment by rvelhote** [comment]
Most likely the issue is that the API that Magento used to create the chart was [deprecated](Google Chart API Deprecated 14th March 2019) on March 14th. That issue is fixed in Magento 1.9.4.1. If for some reason you cannot update you can also try a [module](https://github.com/onilab/magento-1-google-api-chart-fix) that fixes this issue.

**Comment by felipegomesdev** [comment]
Many thanks for the tip @rvelhote . It worked for me. I had applied the fix "Admin Dashboard Charts Patch" but it did not work very well.
