### ISSUE TITLE
Varien_Io_File has an erratic implementation of cd

### ISSUE THREAD

**Issue by masmrlar** [OpenMage/magento-lts#66]
``` php
    /**
     * Change current working directory
     *
     * @param string $dir
     * @return boolean
     */
    public function cd($dir)
    {
        if( is_dir($dir) ) {
            @chdir($this->_iwd);
            $this->_cwd = realpath($dir);
            return true;
        } else {
            throw new Exception('Unable to list current working directory.');
            return false;
        }
    }
```

The thrown exception is superflous and breaks the interface.

**Comment by drobinson** [comment]
I would say either we remove the exception or add @throws and insert error catching in all places in core using cd().

Seems there's no error checking now for any of those usages anyway (which seems like a pretty big oversight) so it may be best to add it in all of those places now...

Do you have thoughts on this @masmrlar?

**Comment by seansan** [comment]
@Flyingmana @masmrlar Is this still an issue? (I see a pull request)

**Comment by Flyingmana** [comment]
The referred PullRequest comes from a different repository, and is related to a different Issue (updating Magento)

For this Topic here, I would instead of trying to change anything there, put out the recommendation to use a better supported library for File/Directory Access.
We dont know, which code and impmenentations out there will break in unexpected ways because of a removed exception.
So I would suggest adding a `@throw`

Also I would not add any error checking at the moment, as this would mean we expect this error there, but we very likely dont know what others expect if this error happens. Also it would change the current error behaviour a lot.

Means: if we have an exception there, and it bubbles up to the top, than it has very likely a good reason for this.

**Comment by mattdavenport** [comment]
Just pushed a PR for this one. I also removed `return false`, as it was an unreachable statement.

**Comment by sreichel** [comment]
@all-contributors add @masmrlar bug
