### ISSUE TITLE
composer.json PHP minimum Requirement => 7.x

### ISSUE THREAD

**Issue by kkrieger85** [OpenMage/magento-lts#691]
Replaces #412 

Update PHP minimum requirements to 7.1. for at least 1.9.4.x branch

Question: Also use php min req to 7.x for 1.9.3.x? We could add https://github.com/Inchoo/Inchoo_PHP7 to composer.json requirements

reference: https://php.net/supported-versions.php

**Comment by Flyingmana** [comment]
there was a comment, that there are current LTS OperatingSystems shipping with a 5.x release, are they out of support now already?

**Comment by colinmollenhour** [comment]
Ubuntu 14.04 LTS is now EOL (as of April 2019). Ubuntu 16.04 LTS uses PHP 7.0.

Do we care about RHEL/CentOS? I don't think we should because do we really want to support PHP 5.4 until June 2024?

**Comment by kkrieger85** [comment]
From my point of view, there is no need to support PHP 5.x. 

There's the [Inchoo/PHP7](https://github.com/Inchoo/Inchoo_PHP7) package which brings PHP7 [Support to Magento Core from 1.9.2.2. upon](https://github.com/Inchoo/Inchoo_PHP7#compatibility)

With Magento Core 1.9.4.x this package was included in Magento Core


Besides that: We can strongly recommend using PHP7 at least for performance reasons

**Comment by colinmollenhour** [comment]
My vote is for 7.0 to be the minimum since it isn't that old and is still supported by Ubuntu 16.04 LTS for two more years.

Debian 8 still uses 5.6 and will not be EOL for 11 more months, but there is an upgrade path to Debian 9 which uses 7.0.

Of course, for people using Docker (which I advocate should be everyone) which distro you run doesn't matter. The official docker images actually stopped supporting 7.0 already with 7.1 being the oldest getting updates.

**Comment by Flyingmana** [comment]
then Iam fine with it, too.

**Comment by sreichel** [comment]
>Question: Also use php min req to 7.x for 1.9.3.x?

I'd leave 1.9.3x as it is ... just add official patches (?), all other changes should be 1.9.4.x only.

**Comment by Flyingmana** [comment]
done via #736
