### ISSUE TITLE
Idea: Fixing error email adresses

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#814]
We are seeing sporadic typos of email addresses where it is pretty clear what the correct alternative should look like. 

Would it be an idea to have some from->to regex or txt replace field that hooks into email /account storage in admin?

By default the field is empty
if populated it will execute a search and replace line per line
it could look like

[Email adresses correction strings]
hotmIl.com hotmail.com
gmail.nl gmail.com
gmal.com gmail.com

2019-09-23T07:38:03+00:00 DEBUG (7): Invalid Resource : pxxxxxx@mailinator.com looks fake or invalid, please enter a real email address.
2019-09-23T07:38:05+00:00 DEBUG (7): Invalid Resource : anonymous@hotmIl.com looks fake or invalid, please enter a real email address.
2019-09-23T07:49:27+00:00 DEBUG (7): Invalid Resource : mememe@gmail.nl looks fake or invalid, please enter a real email address.
2019-09-23T07:49:27+00:00 DEBUG (7): Invalid Resource : youyouyou@gmal.com looks fake or invalid, please enter a real email address.
2019-09-23T07:49:28+00:00 DEBUG (7): Invalid Resource : emailemailn@gmail.nl looks fake or invalid, please enter a real email address.

I know we are not to fond of "adding" functionality but I dont expect this to be breaking. And yes this could be done via an extension. But it could also be a simple core feature.

**Comment by tmotyl** [comment]
@seansan Do you mean emails customer use to register or place order?
If yes, this should be a role of validation. We should not change data customer provided us, and regex always sounds easy, but is complex at the end and error prone (including opening security issues).

What would be useful (and more universal) is an email vaildation based on MX records for domain -> when user registers Magento check if there is an valid MX record for given domain, if not returns an validation error.

**Comment by colinmollenhour** [comment]
Agreed that client-side is the correct place to add this validation since the user knows their own email best, as fat as their fingers may be. However, I could see cases where the admin just wants to override the user-provided data regardless and if it was done server-side then it wouldn't break anyone's templates and it could be done even early in the checkout so the user would still have an opportunity to see the correction before their order was placed. So I'd be for it depending on the implementation.

The MX validation would be a nice universally useful feature as well. However you'd be exposing your server's DNS client to the public without even requiring a successful checkout first. There was a `gethostbyname` vulnerability in libc a while back that probably would have been exploitable given this scenario (CVE-2015-0235). Of course that is water under the bridge now but something to keep in mind. E.g. would probably want to first use `filter_var` or `preg_replace` to get rid of any potentially dangerous characters.

**Comment by sreichel** [comment]
Client side ...

I'd close to do some cleanup. Please reopen if its still an issue.
