### ISSUE TITLE
Migration and Password Length in ver 1.9.4.3 

### ISSUE THREAD

**Issue by kiatng** [OpenMage/magento-lts#850]
I am migrating an existing mage to ver 1.9.4.3. When I failed to login in frontend after the update, I discovered that there is a hardcoded minimum password length which is set to 7. See [commit 99b772](https://github.com/OpenMage/magento-lts/commit/99b772f94de693228a787d69254911e060934cf1). The production has tens of thousands of regular customers. What is the best approach:

1. Get customers whose password length is 6 and can't login to click on _Forgot Your Password?_ and get them to reset the passwords.
2. Change `Mage_Core_Model_App::ABSOLUTE_MIN_PASSWORD_LENGTH` to 6.
3. Make min paswword length configurable.
4. Other approach.

**Comment by colinmollenhour** [comment]
Seems the minimum password length should only apply when *setting* a password, not to existing passwords... Is this an intentional behavior of M1 to block logins by users with short passwords?

**Comment by kiatng** [comment]
I cannot find any reference in the [realease note](https://devdocs.magento.com/guides/m1x/ce19-ee114/ce1.9_release-notes.html#ce19-1943) to increase the min password length. In the code, it just states:

    /**
     * The absolute minimum of password length for all types of passwords
     *
     * With changing this value also need to change:
     * 1. in `js/prototype/validation.js` declarations `var minLength = 7;` in two places;
     * 2. in `app/code/core/Mage/Customer/etc/system.xml`
     *    comments for fields `min_password_length` and `min_admin_password_length`
     *    `<comment>Please enter a number 7 or greater in this field.</comment>`;
     * 3. in `app/code/core/Mage/Customer/etc/config.xml` value `<min_password_length>7</min_password_length>`
     *    and, maybe, value `<min_admin_password_length>14</min_admin_password_length>`
     *    (if the absolute minimum of password length is higher then this value);
     * 4. maybe, the value of deprecated `const MIN_PASSWORD_LENGTH` in `app/code/core/Mage/Admin/Model/User.php`,
     *    (if the absolute minimum of password length is higher then this value).
     */
    const ABSOLUTE_MIN_PASSWORD_LENGTH = 7;

As it states, it now applies min length to both backend and frontend login. For users with password length of 6, when login, the validation error is 

> Please enter more characters or clean leading or trailing spaces. 

which is not the real reason. 

[Password guideline](https://en.wikipedia.org/wiki/Password_strength) recommends 12 characters. So it seems best to keep the `ABSOLUTE_MIN_PASSWORD_LENGTH` as is, configure a higher length requriement in the backend > System, get the store owner to send out emails to customers, and have a better validation error message.

**Comment by fballiano** [comment]
the problem happens because of js/prototype/validation.js

```
    ['validate-password', 'Please enter more characters or clean leading or trailing spaces.', function(v, elm) {
                var pass=v.strip(); /*strip leading and trailing spaces*/
                var reMin = new RegExp(/^min-pass-length-[0-9]+$/);
                var minLength = 6;
                $w(elm.className).each(function(name, index) {
                    if (name.match(reMin)) {
                        minLength = name.split('-')[3];
                    }
                });
                return (!(v.length > 0 && v.length < minLength) && v.length == pass.length);
            }],
```

**Comment by colinmollenhour** [comment]
In my opinion the 7 should be changed to 6 since that was the old value. Otherwise users with shorter passwords are completely locked out! The server-side validation will still enforce the new requirement when setting the password. Also this is just JS validation so it's not like it actually has any impact on security, it's just a potential pain point for customers.

**Comment by kiatng** [comment]
We migrated a production site smoothly. Before the Mage update, when thw user login password is 6, he would be redirected to change password page. After a couple of weeks, we upgraded Mage. For returning users who have not updated, they are asked to change passwords.

**Comment by Rantti** [comment]
@kiatng did you use any certain module or did you implement a custom solution for this?

**Comment by kiatng** [comment]
We implemented it outselves.

**Comment by ADDISON74** [comment]
Even this issue is closed I would like to add a few more comments:

1 - There are a few hard coded texts related to minim length of 6 characters for password in templates and language translations. In my opinion this is a wrong approach that should be fixed. 

Here they are:

/app/design/adminhtml/default/default/template/page/js/translate.phtml
/app/locale/en_US/Mage_Adminthml.csv
/app/locale/en_US/Mage_Core.csv
/app/locale/en_US/Mage_Customer.csv

Checking the files content you will find "Please enter 6 or more characters." or "Please enter 6 or more characters without leading or trailing spaces."

**Why 6 when ABSOLUTE_MIN_PASSWORD_LENGTH is 7?**

2 - Go to https://[domain.tld]/customer/account/create/ to create a new account. Just insert 4 characters into password field and press Send button. I get from time to time two different red texts bellow the input box as follows:

"The password must have at least 6 characters. Leading or trailing spaces will be ignored."
"Please enter more characters or clean leading or trailing spaces."

It is crazy to see 6 characters and if your password matches to 6 characters you will get after pressing Send button an error that you should have 7 characters.

**Comment by kiatng** [comment]
@ADDISON74 The first two translation files are not related to frontend. Note that the backend password is now default to 14, the minimum allowed is 7 characters. See default setting in [customer config.xml](https://github.com/OpenMage/magento-lts/blob/71f903805c1cd959fc4a06ab1eab15c052169f1c/app/code/core/Mage/Customer/etc/config.xml#L605). (I think the default is set in the wrong file, should be in [admin config](https://github.com/OpenMage/magento-lts/blob/1.9.4.x/app/code/core/Mage/Admin/etc/config.xml#L94) instead.) As for the frontend, the translation texts `The password must have at least 6 characters. Leading or trailing spaces will be ignored.` in the last two files can probably be removed, but it shouldn't cause any issue if remain.

On point 2, I have not come across 2 different red texts. What I see is this

![image](https://user-images.githubusercontent.com/1106470/97100140-4b27be00-16cb-11eb-934c-9d432ab5dbb7.png)

which is consistent with `rwd` design package. If you are using a custom template, you need to check where the inconsistency come from.

**Comment by ADDISON74** [comment]
@kiatng: I appreciate your explanation. You gave me a good tip related to theme. Indeed I am using a custom one and I will fix that error message inconsistency.

**Comment by maximehuran** [comment]
To allow existing users to log in with their current password (less than 7 characters), I changed the login.phtml and add this class to the password fields : min-pass-length-5

Customers can now login with a password of 5 characters. If they sign up or change their password, the min length will be 7.
