### ISSUE TITLE
should allow to login with existing short password

### ISSUE THREAD

**Issue by onlinebizsoft** [OpenMage/magento-lts#855]
Right now, the system even prevent customers from logging with an existing weak password. The best scenario should be allowing login with any existing password without validation and just apply validation to new password (new signup, change password)

**Comment by onlinebizsoft** [comment]
https://github.com/OpenMage/magento-lts/issues/850

**Comment by Flyingmana** [comment]
Thats not a bad idea.

If we make it configurable, merchants can decide by themself, if they want to disable it for the login process.

I would still say, the default should respect the limit.

**Comment by kiatng** [comment]
Ref [commit 99b772](https://github.com/OpenMage/magento-lts/commit/99b772f94de693228a787d69254911e060934cf1#diff-176):

![image](https://user-images.githubusercontent.com/1106470/69002234-ae3e9b80-0925-11ea-91ec-5d6110da4cfe.png)

The min password length was 6 in frontend and 7 in backend. So, in order to allow login with existing passwords in v1.9.4.3, the easiest way is to set

    // Mage_Core_Model_App
    const ABSOLUTE_MIN_PASSWORD_LENGTH = 6;

or alternatively, make the min value configurable in backend. This will make it less disruption to upgrade; however, for sites that do want to have better security, only small changes are needed to smooth the transition.

I recently upgraded a production site where the owner decided to take the core as is. Before the upgrade, we added observer at frontend login to redirect users to My Account > Change password for password length = 6. This was done before the upgrade and went on for some days. After the upgrade, we added a warning for users who haven't increased the length:

![image](https://user-images.githubusercontent.com/1106470/69002327-f6f75400-0927-11ea-9d57-7e1155d2d7dd.png)

and at registration we added the length requirement:

![image](https://user-images.githubusercontent.com/1106470/69002340-3160f100-0928-11ea-8fbe-741fee5e86c8.png)

That went well so far. My take is that there is no need to change the core, because for merchants who have decided to upgade to v1.9.4.3, they might as well get the developers to add some code to take care of the transition.

**Comment by fballiano** [comment]
hope this comment will be useful:
https://github.com/OpenMage/magento-lts/issues/850#issuecomment-581866915

**Comment by luigifab** [comment]
+1 I think it's a very bad user experience to refuse customers from logging with an existing weak password.

**Comment by sreichel** [comment]
> +1 I think it's a very bad user experience to refuse customers from logging with an existing weak password.

If you do not enforce users to change passwords these security updates are worthless.

One time change/security > experience . Not optional. Leave a nice message and your customsers will agree with that ...

**Comment by colinmollenhour** [comment]
> One time change/security > experience . Not optional. Leave a nice message and your customsers will agree with that ...

It's the breaking of the login form so that they cannot login in the first place that I disagree with. If they can't login with the old password, I suppose they could use "forgot password" to reset it but they might not think of that and instead think your website sucks and bounce.. lost customer.

**Comment by kiatng** [comment]
Both sides provide valid arguments. It's not difficult to do some code fixes to provide a somewhat smooth transition in existing stores, but it may not be the case for all stores. It's not easy to upgrade to 1.9.4.3. But if the length was 6 in the upgrade, we probbaly wouldn't bother to transition to higher length. 

Is there a middle ground? Perhaps adding some code startng in 1.9.4.3 to help stores transition.

**Comment by kiatng** [comment]
Ideas on "transition" code. 
1. Keep the min length to 7. 
2. Configurable transition period, an end date by which password length is enforced. Or a number of logins beyond which password length will be enforced.
3. Some UI in the frontend to inform customers. Keep in mind that not all customers are affected. Redirect to change password if min length is not met.
4. Provide reporting on progress, but need to gather data on password lengths of customers, probably not good idea.

**Comment by maximehuran** [comment]
To allow existing users to log in with their current password (less than 7 characters), I changed the `login.phtml` and add this class to the password fields : `min-pass-length-5`

Customers can now login with a password of 5 characters. If they sign up or change their password, the min length will be 7.

**Comment by colinmollenhour** [comment]
> Customers can now login with a password of 5 characters. If they sign up or change their password, the min length will be 7.

In my opinion this is the correct solution. Can you create a PR?
