### ISSUE TITLE
My team is in for this.

### ISSUE THREAD

**Issue by Adel-Magebinary** [OpenMage/magento-lts#971]
Hi guys,

Thanks for creating this repo and maintaining it. I somehow find this out today on LinkedIn. 

Please feel free to let my team (team@magebinary.com) know for assigning tickets. We will do our best to contribute to this repo. 

Thanks,
Adel @MageBinary team.

**Comment by tmotyl** [comment]
Hi
Thanks for showing initiative!
You can start with reviewing and testing Pull Requests, there are many which requires one more review to get merged.

For an easy start you can review patches tagged with "doc block update" label:
https://github.com/OpenMage/magento-lts/pulls?q=is%3Apr+is%3Aopen+label%3A%22Project+Cleanup%3A+DOC+blocks%22+

I also encourage you and your team to join OpenMage discord: https://discord.gg/9C6BAr
Please let me know if you have further questions.

**Comment by colinmollenhour** [comment]
Added with Triage role for now.

**Comment by Flyingmana** [comment]
Also a welcome from me.

There are many different ways to help.
As already mentioned, we can always need Reviews for existing Pull Requests, as we have a policy of at least 2 approving Reviewers for a Pull Request to get merged (there may currently be exceptions, because its sometimes hard to get them together)

As the question of How to help comes more often, I also started a Page to list many.
http://www.openmage.org/partners/what-you-can-do.html

If there are questions, feel free to open another Issue, or contact us in the linked chat
